/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

export const getGetConnectionStatusResponseMock = (): boolean =>
	faker.datatype.boolean();

export const getDisconnectResponseMock = (): string[] =>
	Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, () =>
		faker.word.sample(),
	);
