/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  Connection,
  HTTPValidationError
} from '../model';





/**
 * @summary Connect
 */
export type connectResponse200 = {
  data: unknown
  status: 200
}

export type connectResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type connectResponseSuccess = (connectResponse200) & {
  headers: Headers;
};
export type connectResponseError = (connectResponse422) & {
  headers: Headers;
};

export type connectResponse = (connectResponseSuccess | connectResponseError)

export const getConnectUrl = () => {




  return `/connect`
}

export const connect = async (connection: Connection, options?: RequestInit): Promise<connectResponse> => {

  const res = await fetch(getConnectUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      connection,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: connectResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as connectResponse
}




export const getConnectMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connect>>, TError,{data: Connection}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof connect>>, TError,{data: Connection}, TContext> => {

const mutationKey = ['connect'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connect>>, {data: Connection}> = (props) => {
          const {data} = props ?? {};

          return  connect(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectMutationResult = NonNullable<Awaited<ReturnType<typeof connect>>>
    export type ConnectMutationBody = Connection
    export type ConnectMutationError = HTTPValidationError

    /**
 * @summary Connect
 */
export const useConnect = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connect>>, TError,{data: Connection}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connect>>,
        TError,
        {data: Connection},
        TContext
      > => {
      return useMutation(getConnectMutationOptions(options), queryClient);
    }
    /**
 * @summary Disconnect Route
 */
export type disconnectResponse200 = {
  data: string[]
  status: 200
}

export type disconnectResponseSuccess = (disconnectResponse200) & {
  headers: Headers;
};
;

export type disconnectResponse = (disconnectResponseSuccess)

export const getDisconnectUrl = () => {




  return `/connect`
}

export const disconnect = async ( options?: RequestInit): Promise<disconnectResponse> => {

  const res = await fetch(getDisconnectUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: disconnectResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as disconnectResponse
}




export const getDisconnectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnect>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof disconnect>>, TError,void, TContext> => {

const mutationKey = ['disconnect'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disconnect>>, void> = () => {


          return  disconnect(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DisconnectMutationResult = NonNullable<Awaited<ReturnType<typeof disconnect>>>

    export type DisconnectMutationError = unknown

    /**
 * @summary Disconnect Route
 */
export const useDisconnect = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnect>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disconnect>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDisconnectMutationOptions(options), queryClient);
    }
