repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
        args: [--fix, --select, I]

  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        entry: npx @biomejs/biome check --write
        language: system
        types_or: [javascript, jsx, ts, tsx, json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-added-large-files
