# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-06T16:30:55+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Model(BaseModel):
    __root__: Any


class Statistics(BaseModel):
    discontinuity_time: str | None = Field(None, alias='discontinuity-time')
    in_octets: int | None = Field(None, alias='in-octets')
    in_unicast_pkts: int | None = Field(None, alias='in-unicast-pkts')
    in_broadcast_pkts: int | None = Field(None, alias='in-broadcast-pkts')
    in_multicast_pkts: int | None = Field(None, alias='in-multicast-pkts')
    in_discards: int | None = Field(None, alias='in-discards')
    in_errors: int | None = Field(None, alias='in-errors')
    in_unknown_protos: int | None = Field(None, alias='in-unknown-protos')
    out_octets: int | None = Field(None, alias='out-octets')
    out_unicast_pkts: int | None = Field(None, alias='out-unicast-pkts')
    out_broadcast_pkts: int | None = Field(None, alias='out-broadcast-pkts')
    out_multicast_pkts: int | None = Field(None, alias='out-multicast-pkts')
    out_discards: int | None = Field(None, alias='out-discards')
    out_errors: int | None = Field(None, alias='out-errors')


class InterfaceItem(BaseModel):
    name: str | None = None
    description: str | None = None
    type: str | None = None
    enabled: bool | None = None
    link_up_down_trap_enable: str | None = Field(None, alias='link-up-down-trap-enable')
    admin_status: str | None = Field(None, alias='admin-status')
    oper_status: str | None = Field(None, alias='oper-status')
    last_change: str | None = Field(None, alias='last-change')
    if_index: int | None = Field(None, alias='if-index')
    phys_address: str | None = Field(None, alias='phys-address')
    higher_layer_if: list[str] | None = Field(None, alias='higher-layer-if')
    lower_layer_if: list[str] | None = Field(None, alias='lower-layer-if')
    speed: int | None = None
    statistics: Statistics | None = None


class IetfInterfacesInterfaces(BaseModel):
    interface: list[InterfaceItem] | None = None


class InterfaceItem1(BaseModel):
    name: str | None = None
    type: str | None = None
    admin_status: str | None = Field(None, alias='admin-status')
    oper_status: str | None = Field(None, alias='oper-status')
    last_change: str | None = Field(None, alias='last-change')
    if_index: int | None = Field(None, alias='if-index')
    phys_address: str | None = Field(None, alias='phys-address')
    higher_layer_if: list[str] | None = Field(None, alias='higher-layer-if')
    lower_layer_if: list[str] | None = Field(None, alias='lower-layer-if')
    speed: int | None = None
    statistics: Statistics | None = None


class IetfInterfacesInterfacesState(BaseModel):
    interface: list[InterfaceItem1] | None = None
