import type { paths, components } from "./lib/api/v1.d.ts"; // generated by openapi-typescript
import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";


const fetchClient = createFetchClient<paths>({
  baseUrl: "https://myapi.dev/v1/",
});
const $api = createClient(fetchClient);

const { data, error, response } = await client.GET("/test");

type Connection = components["schemas"]["Connection"];
type EndpointParams = paths["/my/endpoint"]["parameters"];
function App() {
  return (
    <>
    </>
  )
}

export default App
