/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	DataStore,
	EditConfigBody,
	GetData200,
	GetModuleData200,
	GetStaged200,
	HTTPValidationError,
} from "../model";

export type copyConfigToResponse204 = {
	data: void;
	status: 204;
};

export type copyConfigToResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type copyConfigToResponseSuccess = copyConfigToResponse204 & {
	headers: Headers;
};
export type copyConfigToResponseError = copyConfigToResponse422 & {
	headers: Headers;
};

export type copyConfigToResponse =
	| copyConfigToResponseSuccess
	| copyConfigToResponseError;

export const getCopyConfigToUrl = (source: DataStore, target: DataStore) => {
	return `/api/v1/datastore/${source}/copy-config/${target}`;
};

/**
 * @summary Copy Config
 */
export const copyConfigTo = async (
	source: DataStore,
	target: DataStore,
	options?: RequestInit,
): Promise<copyConfigToResponse> => {
	const res = await fetch(getCopyConfigToUrl(source, target), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: copyConfigToResponse["data"] = body
		? JSON.parse(body)
		: undefined;
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as copyConfigToResponse;
};

export const getCopyConfigToMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof copyConfigTo>>,
		TError,
		{ source: DataStore; target: DataStore },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof copyConfigTo>>,
	TError,
	{ source: DataStore; target: DataStore },
	TContext
> => {
	const mutationKey = ["copyConfigTo"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof copyConfigTo>>,
		{ source: DataStore; target: DataStore }
	> = (props) => {
		const { source, target } = props ?? {};

		return copyConfigTo(source, target, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CopyConfigToMutationResult = NonNullable<
	Awaited<ReturnType<typeof copyConfigTo>>
>;

export type CopyConfigToMutationError = HTTPValidationError;

/**
 * @summary Copy Config
 */
export const useCopyConfigTo = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof copyConfigTo>>,
			TError,
			{ source: DataStore; target: DataStore },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof copyConfigTo>>,
	TError,
	{ source: DataStore; target: DataStore },
	TContext
> => {
	return useMutation(getCopyConfigToMutationOptions(options), queryClient);
};
export type deleteConfigResponse204 = {
	data: void;
	status: 204;
};

export type deleteConfigResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type deleteConfigResponseSuccess = deleteConfigResponse204 & {
	headers: Headers;
};
export type deleteConfigResponseError = deleteConfigResponse422 & {
	headers: Headers;
};

export type deleteConfigResponse =
	| deleteConfigResponseSuccess
	| deleteConfigResponseError;

export const getDeleteConfigUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}`;
};

/**
 * @summary Delete Config
 */
export const deleteConfig = async (
	dataStore: DataStore,
	options?: RequestInit,
): Promise<deleteConfigResponse> => {
	const res = await fetch(getDeleteConfigUrl(dataStore), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: deleteConfigResponse["data"] = body
		? JSON.parse(body)
		: undefined;
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as deleteConfigResponse;
};

export const getDeleteConfigMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteConfig>>,
		TError,
		{ dataStore: DataStore },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteConfig>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	const mutationKey = ["deleteConfig"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteConfig>>,
		{ dataStore: DataStore }
	> = (props) => {
		const { dataStore } = props ?? {};

		return deleteConfig(dataStore, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteConfigMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteConfig>>
>;

export type DeleteConfigMutationError = HTTPValidationError;

/**
 * @summary Delete Config
 */
export const useDeleteConfig = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteConfig>>,
			TError,
			{ dataStore: DataStore },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteConfig>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	return useMutation(getDeleteConfigMutationOptions(options), queryClient);
};
export type lockDatastoreResponse204 = {
	data: void;
	status: 204;
};

export type lockDatastoreResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type lockDatastoreResponseSuccess = lockDatastoreResponse204 & {
	headers: Headers;
};
export type lockDatastoreResponseError = lockDatastoreResponse422 & {
	headers: Headers;
};

export type lockDatastoreResponse =
	| lockDatastoreResponseSuccess
	| lockDatastoreResponseError;

export const getLockDatastoreUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}/lock`;
};

/**
 * @summary Lock
 */
export const lockDatastore = async (
	dataStore: DataStore,
	options?: RequestInit,
): Promise<lockDatastoreResponse> => {
	const res = await fetch(getLockDatastoreUrl(dataStore), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: lockDatastoreResponse["data"] = body
		? JSON.parse(body)
		: undefined;
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as lockDatastoreResponse;
};

export const getLockDatastoreMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof lockDatastore>>,
		TError,
		{ dataStore: DataStore },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof lockDatastore>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	const mutationKey = ["lockDatastore"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof lockDatastore>>,
		{ dataStore: DataStore }
	> = (props) => {
		const { dataStore } = props ?? {};

		return lockDatastore(dataStore, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LockDatastoreMutationResult = NonNullable<
	Awaited<ReturnType<typeof lockDatastore>>
>;

export type LockDatastoreMutationError = HTTPValidationError;

/**
 * @summary Lock
 */
export const useLockDatastore = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof lockDatastore>>,
			TError,
			{ dataStore: DataStore },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof lockDatastore>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	return useMutation(getLockDatastoreMutationOptions(options), queryClient);
};
export type unlockDatastoreResponse204 = {
	data: void;
	status: 204;
};

export type unlockDatastoreResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type unlockDatastoreResponseSuccess = unlockDatastoreResponse204 & {
	headers: Headers;
};
export type unlockDatastoreResponseError = unlockDatastoreResponse422 & {
	headers: Headers;
};

export type unlockDatastoreResponse =
	| unlockDatastoreResponseSuccess
	| unlockDatastoreResponseError;

export const getUnlockDatastoreUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}/lock`;
};

/**
 * @summary Unlock
 */
export const unlockDatastore = async (
	dataStore: DataStore,
	options?: RequestInit,
): Promise<unlockDatastoreResponse> => {
	const res = await fetch(getUnlockDatastoreUrl(dataStore), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: unlockDatastoreResponse["data"] = body
		? JSON.parse(body)
		: undefined;
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as unlockDatastoreResponse;
};

export const getUnlockDatastoreMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof unlockDatastore>>,
		TError,
		{ dataStore: DataStore },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof unlockDatastore>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	const mutationKey = ["unlockDatastore"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof unlockDatastore>>,
		{ dataStore: DataStore }
	> = (props) => {
		const { dataStore } = props ?? {};

		return unlockDatastore(dataStore, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UnlockDatastoreMutationResult = NonNullable<
	Awaited<ReturnType<typeof unlockDatastore>>
>;

export type UnlockDatastoreMutationError = HTTPValidationError;

/**
 * @summary Unlock
 */
export const useUnlockDatastore = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof unlockDatastore>>,
			TError,
			{ dataStore: DataStore },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof unlockDatastore>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	return useMutation(getUnlockDatastoreMutationOptions(options), queryClient);
};
export type getLockResponse200 = {
	data: boolean;
	status: 200;
};

export type getLockResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getLockResponseSuccess = getLockResponse200 & {
	headers: Headers;
};
export type getLockResponseError = getLockResponse422 & {
	headers: Headers;
};

export type getLockResponse = getLockResponseSuccess | getLockResponseError;

export const getGetLockUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}/lock`;
};

/**
 * @summary Get Lock Info
 */
export const getLock = async (
	dataStore: DataStore,
	options?: RequestInit,
): Promise<getLockResponse> => {
	const res = await fetch(getGetLockUrl(dataStore), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getLockResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getLockResponse;
};

export const getGetLockQueryKey = (dataStore: DataStore) => {
	return [`/api/v1/datastore/${dataStore}/lock`] as const;
};

export const getGetLockQueryOptions = <
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetLockQueryKey(dataStore);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getLock>>> = ({
		signal,
	}) => getLock(dataStore, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: dataStore !== null && dataStore !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetLockQueryResult = NonNullable<
	Awaited<ReturnType<typeof getLock>>
>;
export type GetLockQueryError = HTTPValidationError;

export function useGetLock<
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getLock>>,
					TError,
					Awaited<ReturnType<typeof getLock>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLock<
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getLock>>,
					TError,
					Awaited<ReturnType<typeof getLock>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLock<
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Lock Info
 */

export function useGetLock<
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetLockQueryOptions(dataStore, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type getModuleDataResponse200 = {
	data: GetModuleData200;
	status: 200;
};

export type getModuleDataResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getModuleDataResponseSuccess = getModuleDataResponse200 & {
	headers: Headers;
};
export type getModuleDataResponseError = getModuleDataResponse422 & {
	headers: Headers;
};

export type getModuleDataResponse =
	| getModuleDataResponseSuccess
	| getModuleDataResponseError;

export const getGetModuleDataUrl = (
	dataStore: DataStore,
	moduleName: string,
) => {
	return `/api/v1/datastore/${dataStore}/${moduleName}/data`;
};

/**
 * @summary Get Module Data
 */
export const getModuleData = async (
	dataStore: DataStore,
	moduleName: string,
	options?: RequestInit,
): Promise<getModuleDataResponse> => {
	const res = await fetch(getGetModuleDataUrl(dataStore, moduleName), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getModuleDataResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getModuleDataResponse;
};

export const getGetModuleDataQueryKey = (
	dataStore: DataStore,
	moduleName: string,
) => {
	return [`/api/v1/datastore/${dataStore}/${moduleName}/data`] as const;
};

export const getGetModuleDataQueryOptions = <
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetModuleDataQueryKey(dataStore, moduleName);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleData>>> = ({
		signal,
	}) => getModuleData(dataStore, moduleName, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled:
			dataStore !== null &&
			dataStore !== undefined &&
			moduleName !== null &&
			moduleName !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getModuleData>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetModuleDataQueryResult = NonNullable<
	Awaited<ReturnType<typeof getModuleData>>
>;
export type GetModuleDataQueryError = HTTPValidationError;

export function useGetModuleData<
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getModuleData>>,
					TError,
					Awaited<ReturnType<typeof getModuleData>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetModuleData<
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getModuleData>>,
					TError,
					Awaited<ReturnType<typeof getModuleData>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetModuleData<
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Module Data
 */

export function useGetModuleData<
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetModuleDataQueryOptions(
		dataStore,
		moduleName,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type getDataResponse200 = {
	data: GetData200;
	status: 200;
};

export type getDataResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getDataResponseSuccess = getDataResponse200 & {
	headers: Headers;
};
export type getDataResponseError = getDataResponse422 & {
	headers: Headers;
};

export type getDataResponse = getDataResponseSuccess | getDataResponseError;

export const getGetDataUrl = (
	dataStore: DataStore,
	moduleName: string,
	path: string,
) => {
	return `/api/v1/datastore/${dataStore}/${moduleName}/data/${path}`;
};

/**
 * @summary Get Data
 */
export const getData = async (
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: RequestInit,
): Promise<getDataResponse> => {
	const res = await fetch(getGetDataUrl(dataStore, moduleName, path), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getDataResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getDataResponse;
};

export const getGetDataQueryKey = (
	dataStore: DataStore,
	moduleName: string,
	path: string,
) => {
	return [`/api/v1/datastore/${dataStore}/${moduleName}/data/${path}`] as const;
};

export const getGetDataQueryOptions = <
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDataQueryKey(dataStore, moduleName, path);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getData>>> = ({
		signal,
	}) => getData(dataStore, moduleName, path, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled:
			dataStore !== null &&
			dataStore !== undefined &&
			moduleName !== null &&
			moduleName !== undefined &&
			path !== null &&
			path !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetDataQueryResult = NonNullable<
	Awaited<ReturnType<typeof getData>>
>;
export type GetDataQueryError = HTTPValidationError;

export function useGetData<
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getData>>,
					TError,
					Awaited<ReturnType<typeof getData>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetData<
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getData>>,
					TError,
					Awaited<ReturnType<typeof getData>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetData<
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Data
 */

export function useGetData<
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDataQueryOptions(
		dataStore,
		moduleName,
		path,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type editConfigResponse204 = {
	data: void;
	status: 204;
};

export type editConfigResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type editConfigResponseSuccess = editConfigResponse204 & {
	headers: Headers;
};
export type editConfigResponseError = editConfigResponse422 & {
	headers: Headers;
};

export type editConfigResponse =
	| editConfigResponseSuccess
	| editConfigResponseError;

export const getEditConfigUrl = (
	dataStore: DataStore,
	moduleName: string,
	path: string,
) => {
	return `/api/v1/datastore/${dataStore}/${moduleName}/data/${path}`;
};

/**
 * @summary Edit Config
 */
export const editConfig = async (
	dataStore: DataStore,
	moduleName: string,
	path: string,
	editConfigBody: EditConfigBody,
	options?: RequestInit,
): Promise<editConfigResponse> => {
	const res = await fetch(getEditConfigUrl(dataStore, moduleName, path), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(editConfigBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: editConfigResponse["data"] = body ? JSON.parse(body) : undefined;
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as editConfigResponse;
};

export const getEditConfigMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof editConfig>>,
		TError,
		{
			dataStore: DataStore;
			moduleName: string;
			path: string;
			data: EditConfigBody;
		},
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof editConfig>>,
	TError,
	{
		dataStore: DataStore;
		moduleName: string;
		path: string;
		data: EditConfigBody;
	},
	TContext
> => {
	const mutationKey = ["editConfig"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof editConfig>>,
		{
			dataStore: DataStore;
			moduleName: string;
			path: string;
			data: EditConfigBody;
		}
	> = (props) => {
		const { dataStore, moduleName, path, data } = props ?? {};

		return editConfig(dataStore, moduleName, path, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type EditConfigMutationResult = NonNullable<
	Awaited<ReturnType<typeof editConfig>>
>;
export type EditConfigMutationBody = EditConfigBody;
export type EditConfigMutationError = HTTPValidationError;

/**
 * @summary Edit Config
 */
export const useEditConfig = <TError = HTTPValidationError, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof editConfig>>,
			TError,
			{
				dataStore: DataStore;
				moduleName: string;
				path: string;
				data: EditConfigBody;
			},
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof editConfig>>,
	TError,
	{
		dataStore: DataStore;
		moduleName: string;
		path: string;
		data: EditConfigBody;
	},
	TContext
> => {
	return useMutation(getEditConfigMutationOptions(options), queryClient);
};
export type getStagedResponse200 = {
	data: GetStaged200;
	status: 200;
};

export type getStagedResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getStagedResponseSuccess = getStagedResponse200 & {
	headers: Headers;
};
export type getStagedResponseError = getStagedResponse422 & {
	headers: Headers;
};

export type getStagedResponse =
	| getStagedResponseSuccess
	| getStagedResponseError;

export const getGetStagedUrl = (moduleName: string) => {
	return `/api/v1/datastore/staged/${moduleName}`;
};

/**
 * @summary Get Staged
 */
export const getStaged = async (
	moduleName: string,
	options?: RequestInit,
): Promise<getStagedResponse> => {
	const res = await fetch(getGetStagedUrl(moduleName), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getStagedResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getStagedResponse;
};

export const getGetStagedQueryKey = (moduleName: string) => {
	return [`/api/v1/datastore/staged/${moduleName}`] as const;
};

export const getGetStagedQueryOptions = <
	TData = Awaited<ReturnType<typeof getStaged>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getStaged>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetStagedQueryKey(moduleName);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getStaged>>> = ({
		signal,
	}) => getStaged(moduleName, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: moduleName !== null && moduleName !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getStaged>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetStagedQueryResult = NonNullable<
	Awaited<ReturnType<typeof getStaged>>
>;
export type GetStagedQueryError = HTTPValidationError;

export function useGetStaged<
	TData = Awaited<ReturnType<typeof getStaged>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getStaged>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getStaged>>,
					TError,
					Awaited<ReturnType<typeof getStaged>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaged<
	TData = Awaited<ReturnType<typeof getStaged>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getStaged>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getStaged>>,
					TError,
					Awaited<ReturnType<typeof getStaged>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaged<
	TData = Awaited<ReturnType<typeof getStaged>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getStaged>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Staged
 */

export function useGetStaged<
	TData = Awaited<ReturnType<typeof getStaged>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getStaged>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetStagedQueryOptions(moduleName, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type commitResponse204 = {
	data: void;
	status: 204;
};

export type commitResponseSuccess = commitResponse204 & {
	headers: Headers;
};

export type commitResponse = commitResponseSuccess;

export const getCommitUrl = () => {
	return `/api/v1/datastore/commit`;
};

/**
 * @summary Commit
 */
export const commit = async (
	options?: RequestInit,
): Promise<commitResponse> => {
	const res = await fetch(getCommitUrl(), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: commitResponse["data"] = body ? JSON.parse(body) : undefined;
	return { data, status: res.status, headers: res.headers } as commitResponse;
};

export const getCommitMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof commit>>,
		TError,
		void,
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof commit>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["commit"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof commit>>,
		void
	> = () => {
		return commit(fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CommitMutationResult = NonNullable<
	Awaited<ReturnType<typeof commit>>
>;

export type CommitMutationError = unknown;

/**
 * @summary Commit
 */
export const useCommit = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof commit>>,
			TError,
			void,
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof commit>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getCommitMutationOptions(options), queryClient);
};
