/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";

import type { GetData200, GetModuleData200, GetStaged200 } from "../model";

export const getGetLockResponseMock = (): boolean => faker.datatype.boolean();

export const getGetModuleDataResponseMock = (): GetModuleData200 => ({});

export const getGetDataResponseMock = (): GetData200 => ({});

export const getGetStagedResponseMock = (): GetStaged200 => ({});

export const getCopyConfigToMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/v1/datastore/:source/copy-config/:target",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getDeleteConfigMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/api/v1/datastore/:dataStore",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getLockDatastoreMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/v1/datastore/:dataStore/lock",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getUnlockDatastoreMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/api/v1/datastore/:dataStore/lock",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getGetLockMockHandler = (
	overrideResponse?:
		| boolean
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<boolean> | boolean),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/v1/datastore/:dataStore/lock",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetLockResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetModuleDataMockHandler = (
	overrideResponse?:
		| GetModuleData200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetModuleData200> | GetModuleData200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/v1/datastore/:dataStore/:moduleName/data",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetModuleDataResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetDataMockHandler = (
	overrideResponse?:
		| GetData200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetData200> | GetData200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/v1/datastore/:dataStore/:moduleName/data/:path",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetDataResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getEditConfigMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.patch>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.patch(
		"*/api/v1/datastore/:dataStore/:moduleName/data/:path",
		async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getGetStagedMockHandler = (
	overrideResponse?:
		| GetStaged200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetStaged200> | GetStaged200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/v1/datastore/staged/:moduleName",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetStagedResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getCommitMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/v1/datastore/commit",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};
export const getDatastoreMock = () => [
	getCopyConfigToMockHandler(),
	getDeleteConfigMockHandler(),
	getLockDatastoreMockHandler(),
	getUnlockDatastoreMockHandler(),
	getGetLockMockHandler(),
	getGetModuleDataMockHandler(),
	getGetDataMockHandler(),
	getEditConfigMockHandler(),
	getGetStagedMockHandler(),
	getCommitMockHandler(),
];
