/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	DataStore,
	EditConfigRequest,
	GetData200,
	GetModuleData200,
	HTTPValidationError,
} from "../model";

/**
 * @summary Copy Config
 */
export type copyConfigToResponse200 = {
	data: string;
	status: 200;
};

export type copyConfigToResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type copyConfigToResponseSuccess = copyConfigToResponse200 & {
	headers: Headers;
};
export type copyConfigToResponseError = copyConfigToResponse422 & {
	headers: Headers;
};

export type copyConfigToResponse =
	| copyConfigToResponseSuccess
	| copyConfigToResponseError;

export const getCopyConfigToUrl = (source: DataStore, target: DataStore) => {
	return `/api/v1/datastore/${source}/copy-config/${target}`;
};

export const copyConfigTo = async (
	source: DataStore,
	target: DataStore,
	options?: RequestInit,
): Promise<copyConfigToResponse> => {
	const res = await fetch(getCopyConfigToUrl(source, target), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: copyConfigToResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as copyConfigToResponse;
};

export const getCopyConfigToMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof copyConfigTo>>,
		TError,
		{ source: DataStore; target: DataStore },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof copyConfigTo>>,
	TError,
	{ source: DataStore; target: DataStore },
	TContext
> => {
	const mutationKey = ["copyConfigTo"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof copyConfigTo>>,
		{ source: DataStore; target: DataStore }
	> = (props) => {
		const { source, target } = props ?? {};

		return copyConfigTo(source, target, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CopyConfigToMutationResult = NonNullable<
	Awaited<ReturnType<typeof copyConfigTo>>
>;

export type CopyConfigToMutationError = HTTPValidationError;

/**
 * @summary Copy Config
 */
export const useCopyConfigTo = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof copyConfigTo>>,
			TError,
			{ source: DataStore; target: DataStore },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof copyConfigTo>>,
	TError,
	{ source: DataStore; target: DataStore },
	TContext
> => {
	return useMutation(getCopyConfigToMutationOptions(options), queryClient);
};
/**
 * @summary Delete Config
 */
export type deleteConfigResponse200 = {
	data: string;
	status: 200;
};

export type deleteConfigResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type deleteConfigResponseSuccess = deleteConfigResponse200 & {
	headers: Headers;
};
export type deleteConfigResponseError = deleteConfigResponse422 & {
	headers: Headers;
};

export type deleteConfigResponse =
	| deleteConfigResponseSuccess
	| deleteConfigResponseError;

export const getDeleteConfigUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}`;
};

export const deleteConfig = async (
	dataStore: DataStore,
	options?: RequestInit,
): Promise<deleteConfigResponse> => {
	const res = await fetch(getDeleteConfigUrl(dataStore), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: deleteConfigResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as deleteConfigResponse;
};

export const getDeleteConfigMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteConfig>>,
		TError,
		{ dataStore: DataStore },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteConfig>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	const mutationKey = ["deleteConfig"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteConfig>>,
		{ dataStore: DataStore }
	> = (props) => {
		const { dataStore } = props ?? {};

		return deleteConfig(dataStore, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteConfigMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteConfig>>
>;

export type DeleteConfigMutationError = HTTPValidationError;

/**
 * @summary Delete Config
 */
export const useDeleteConfig = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteConfig>>,
			TError,
			{ dataStore: DataStore },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteConfig>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	return useMutation(getDeleteConfigMutationOptions(options), queryClient);
};
/**
 * @summary Lock
 */
export type lockDatastoreResponse200 = {
	data: string;
	status: 200;
};

export type lockDatastoreResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type lockDatastoreResponseSuccess = lockDatastoreResponse200 & {
	headers: Headers;
};
export type lockDatastoreResponseError = lockDatastoreResponse422 & {
	headers: Headers;
};

export type lockDatastoreResponse =
	| lockDatastoreResponseSuccess
	| lockDatastoreResponseError;

export const getLockDatastoreUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}/lock`;
};

export const lockDatastore = async (
	dataStore: DataStore,
	options?: RequestInit,
): Promise<lockDatastoreResponse> => {
	const res = await fetch(getLockDatastoreUrl(dataStore), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: lockDatastoreResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as lockDatastoreResponse;
};

export const getLockDatastoreMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof lockDatastore>>,
		TError,
		{ dataStore: DataStore },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof lockDatastore>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	const mutationKey = ["lockDatastore"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof lockDatastore>>,
		{ dataStore: DataStore }
	> = (props) => {
		const { dataStore } = props ?? {};

		return lockDatastore(dataStore, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LockDatastoreMutationResult = NonNullable<
	Awaited<ReturnType<typeof lockDatastore>>
>;

export type LockDatastoreMutationError = HTTPValidationError;

/**
 * @summary Lock
 */
export const useLockDatastore = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof lockDatastore>>,
			TError,
			{ dataStore: DataStore },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof lockDatastore>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	return useMutation(getLockDatastoreMutationOptions(options), queryClient);
};
/**
 * @summary Unlock
 */
export type unlockDatastoreResponse200 = {
	data: string;
	status: 200;
};

export type unlockDatastoreResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type unlockDatastoreResponseSuccess = unlockDatastoreResponse200 & {
	headers: Headers;
};
export type unlockDatastoreResponseError = unlockDatastoreResponse422 & {
	headers: Headers;
};

export type unlockDatastoreResponse =
	| unlockDatastoreResponseSuccess
	| unlockDatastoreResponseError;

export const getUnlockDatastoreUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}/lock`;
};

export const unlockDatastore = async (
	dataStore: DataStore,
	options?: RequestInit,
): Promise<unlockDatastoreResponse> => {
	const res = await fetch(getUnlockDatastoreUrl(dataStore), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: unlockDatastoreResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as unlockDatastoreResponse;
};

export const getUnlockDatastoreMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof unlockDatastore>>,
		TError,
		{ dataStore: DataStore },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof unlockDatastore>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	const mutationKey = ["unlockDatastore"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof unlockDatastore>>,
		{ dataStore: DataStore }
	> = (props) => {
		const { dataStore } = props ?? {};

		return unlockDatastore(dataStore, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UnlockDatastoreMutationResult = NonNullable<
	Awaited<ReturnType<typeof unlockDatastore>>
>;

export type UnlockDatastoreMutationError = HTTPValidationError;

/**
 * @summary Unlock
 */
export const useUnlockDatastore = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof unlockDatastore>>,
			TError,
			{ dataStore: DataStore },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof unlockDatastore>>,
	TError,
	{ dataStore: DataStore },
	TContext
> => {
	return useMutation(getUnlockDatastoreMutationOptions(options), queryClient);
};
/**
 * @summary Get Lock Info
 */
export type getLockResponse200 = {
	data: boolean;
	status: 200;
};

export type getLockResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getLockResponseSuccess = getLockResponse200 & {
	headers: Headers;
};
export type getLockResponseError = getLockResponse422 & {
	headers: Headers;
};

export type getLockResponse = getLockResponseSuccess | getLockResponseError;

export const getGetLockUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}/lock`;
};

export const getLock = async (
	dataStore: DataStore,
	options?: RequestInit,
): Promise<getLockResponse> => {
	const res = await fetch(getGetLockUrl(dataStore), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getLockResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getLockResponse;
};

export const getGetLockQueryKey = (dataStore: DataStore) => {
	return [`/api/v1/datastore/${dataStore}/lock`] as const;
};

export const getGetLockQueryOptions = <
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetLockQueryKey(dataStore);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getLock>>> = ({
		signal,
	}) => getLock(dataStore, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!dataStore,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetLockQueryResult = NonNullable<
	Awaited<ReturnType<typeof getLock>>
>;
export type GetLockQueryError = HTTPValidationError;

export function useGetLock<
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getLock>>,
					TError,
					Awaited<ReturnType<typeof getLock>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLock<
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getLock>>,
					TError,
					Awaited<ReturnType<typeof getLock>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLock<
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Lock Info
 */

export function useGetLock<
	TData = Awaited<ReturnType<typeof getLock>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getLock>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetLockQueryOptions(dataStore, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Module Data
 */
export type getModuleDataResponse200 = {
	data: GetModuleData200;
	status: 200;
};

export type getModuleDataResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getModuleDataResponseSuccess = getModuleDataResponse200 & {
	headers: Headers;
};
export type getModuleDataResponseError = getModuleDataResponse422 & {
	headers: Headers;
};

export type getModuleDataResponse =
	| getModuleDataResponseSuccess
	| getModuleDataResponseError;

export const getGetModuleDataUrl = (
	dataStore: DataStore,
	moduleName: string,
) => {
	return `/api/v1/datastore/${dataStore}/${moduleName}/data`;
};

export const getModuleData = async (
	dataStore: DataStore,
	moduleName: string,
	options?: RequestInit,
): Promise<getModuleDataResponse> => {
	const res = await fetch(getGetModuleDataUrl(dataStore, moduleName), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getModuleDataResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getModuleDataResponse;
};

export const getGetModuleDataQueryKey = (
	dataStore: DataStore,
	moduleName: string,
) => {
	return [`/api/v1/datastore/${dataStore}/${moduleName}/data`] as const;
};

export const getGetModuleDataQueryOptions = <
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetModuleDataQueryKey(dataStore, moduleName);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleData>>> = ({
		signal,
	}) => getModuleData(dataStore, moduleName, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!(dataStore && moduleName),
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getModuleData>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetModuleDataQueryResult = NonNullable<
	Awaited<ReturnType<typeof getModuleData>>
>;
export type GetModuleDataQueryError = HTTPValidationError;

export function useGetModuleData<
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getModuleData>>,
					TError,
					Awaited<ReturnType<typeof getModuleData>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetModuleData<
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getModuleData>>,
					TError,
					Awaited<ReturnType<typeof getModuleData>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetModuleData<
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Module Data
 */

export function useGetModuleData<
	TData = Awaited<ReturnType<typeof getModuleData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModuleData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetModuleDataQueryOptions(
		dataStore,
		moduleName,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Data
 */
export type getDataResponse200 = {
	data: GetData200;
	status: 200;
};

export type getDataResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getDataResponseSuccess = getDataResponse200 & {
	headers: Headers;
};
export type getDataResponseError = getDataResponse422 & {
	headers: Headers;
};

export type getDataResponse = getDataResponseSuccess | getDataResponseError;

export const getGetDataUrl = (
	dataStore: DataStore,
	moduleName: string,
	path: string,
) => {
	return `/api/v1/datastore/${dataStore}/${moduleName}/data/${path}`;
};

export const getData = async (
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: RequestInit,
): Promise<getDataResponse> => {
	const res = await fetch(getGetDataUrl(dataStore, moduleName, path), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getDataResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getDataResponse;
};

export const getGetDataQueryKey = (
	dataStore: DataStore,
	moduleName: string,
	path: string,
) => {
	return [`/api/v1/datastore/${dataStore}/${moduleName}/data/${path}`] as const;
};

export const getGetDataQueryOptions = <
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDataQueryKey(dataStore, moduleName, path);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getData>>> = ({
		signal,
	}) => getData(dataStore, moduleName, path, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!(dataStore && moduleName && path),
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetDataQueryResult = NonNullable<
	Awaited<ReturnType<typeof getData>>
>;
export type GetDataQueryError = HTTPValidationError;

export function useGetData<
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getData>>,
					TError,
					Awaited<ReturnType<typeof getData>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetData<
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getData>>,
					TError,
					Awaited<ReturnType<typeof getData>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetData<
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Data
 */

export function useGetData<
	TData = Awaited<ReturnType<typeof getData>>,
	TError = HTTPValidationError,
>(
	dataStore: DataStore,
	moduleName: string,
	path: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getData>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDataQueryOptions(
		dataStore,
		moduleName,
		path,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Edit Config
 */
export type editConfigResponse200 = {
	data: string;
	status: 200;
};

export type editConfigResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type editConfigResponseSuccess = editConfigResponse200 & {
	headers: Headers;
};
export type editConfigResponseError = editConfigResponse422 & {
	headers: Headers;
};

export type editConfigResponse =
	| editConfigResponseSuccess
	| editConfigResponseError;

export const getEditConfigUrl = (dataStore: DataStore) => {
	return `/api/v1/datastore/${dataStore}/edit-config`;
};

export const editConfig = async (
	dataStore: DataStore,
	editConfigRequest: EditConfigRequest,
	options?: RequestInit,
): Promise<editConfigResponse> => {
	const res = await fetch(getEditConfigUrl(dataStore), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(editConfigRequest),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: editConfigResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as editConfigResponse;
};

export const getEditConfigMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof editConfig>>,
		TError,
		{ dataStore: DataStore; data: EditConfigRequest },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof editConfig>>,
	TError,
	{ dataStore: DataStore; data: EditConfigRequest },
	TContext
> => {
	const mutationKey = ["editConfig"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof editConfig>>,
		{ dataStore: DataStore; data: EditConfigRequest }
	> = (props) => {
		const { dataStore, data } = props ?? {};

		return editConfig(dataStore, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type EditConfigMutationResult = NonNullable<
	Awaited<ReturnType<typeof editConfig>>
>;
export type EditConfigMutationBody = EditConfigRequest;
export type EditConfigMutationError = HTTPValidationError;

/**
 * @summary Edit Config
 */
export const useEditConfig = <TError = HTTPValidationError, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof editConfig>>,
			TError,
			{ dataStore: DataStore; data: EditConfigRequest },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof editConfig>>,
	TError,
	{ dataStore: DataStore; data: EditConfigRequest },
	TContext
> => {
	return useMutation(getEditConfigMutationOptions(options), queryClient);
};
