/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";

import type { GetData200, GetModuleData200 } from "../model";

export const getCopyConfigToResponseMock = (): string => faker.word.sample();

export const getDeleteConfigResponseMock = (): string => faker.word.sample();

export const getLockDatastoreResponseMock = (): string => faker.word.sample();

export const getUnlockDatastoreResponseMock = (): string => faker.word.sample();

export const getGetLockResponseMock = (): boolean => faker.datatype.boolean();

export const getGetModuleDataResponseMock = (): GetModuleData200 => ({});

export const getGetDataResponseMock = (): GetData200 => ({});

export const getCopyConfigToMockHandler = (
	overrideResponse?:
		| string
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<string> | string),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/v1/datastore/:source/copy-config/:target",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCopyConfigToResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getDeleteConfigMockHandler = (
	overrideResponse?:
		| string
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<string> | string),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/api/v1/datastore/:dataStore",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getDeleteConfigResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getLockDatastoreMockHandler = (
	overrideResponse?:
		| string
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<string> | string),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/v1/datastore/:dataStore/lock",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getLockDatastoreResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUnlockDatastoreMockHandler = (
	overrideResponse?:
		| string
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<string> | string),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/api/v1/datastore/:dataStore/lock",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUnlockDatastoreResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetLockMockHandler = (
	overrideResponse?:
		| boolean
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<boolean> | boolean),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/v1/datastore/:dataStore/lock",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetLockResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetModuleDataMockHandler = (
	overrideResponse?:
		| GetModuleData200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetModuleData200> | GetModuleData200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/v1/datastore/:dataStore/:moduleName/data",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetModuleDataResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetDataMockHandler = (
	overrideResponse?:
		| GetData200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetData200> | GetData200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/v1/datastore/:dataStore/:moduleName/data/:path",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetDataResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};
export const getDatastoreMock = () => [
	getCopyConfigToMockHandler(),
	getDeleteConfigMockHandler(),
	getLockDatastoreMockHandler(),
	getUnlockDatastoreMockHandler(),
	getGetLockMockHandler(),
	getGetModuleDataMockHandler(),
	getGetDataMockHandler(),
];
