/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  Module
} from '../model';





/**
 * @summary Get Modules
 */
export type getModulesResponse200 = {
  data: Module[]
  status: 200
}

export type getModulesResponseSuccess = (getModulesResponse200) & {
  headers: Headers;
};
;

export type getModulesResponse = (getModulesResponseSuccess)

export const getGetModulesUrl = () => {




  return `/modules/`
}

export const getModules = async ( options?: RequestInit): Promise<getModulesResponse> => {

  const res = await fetch(getGetModulesUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getModulesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getModulesResponse
}





export const getGetModulesQueryKey = () => {
    return [
    `/modules/`
    ] as const;
    }


export const getGetModulesQueryOptions = <TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModulesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModules>>> = ({ signal }) => getModules({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getModules>>>
export type GetModulesQueryError = unknown


export function useGetModules<TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModules>>,
          TError,
          Awaited<ReturnType<typeof getModules>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModules<TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModules>>,
          TError,
          Awaited<ReturnType<typeof getModules>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModules<TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Modules
 */

export function useGetModules<TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModulesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Download Module
 */
export type downloadModuleResponse200 = {
  data: unknown
  status: 200
}

export type downloadModuleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type downloadModuleResponseSuccess = (downloadModuleResponse200) & {
  headers: Headers;
};
export type downloadModuleResponseError = (downloadModuleResponse422) & {
  headers: Headers;
};

export type downloadModuleResponse = (downloadModuleResponseSuccess | downloadModuleResponseError)

export const getDownloadModuleUrl = (moduleName: string,) => {




  return `/modules/${moduleName}/download`
}

export const downloadModule = async (moduleName: string, options?: RequestInit): Promise<downloadModuleResponse> => {

  const res = await fetch(getDownloadModuleUrl(moduleName),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: downloadModuleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as downloadModuleResponse
}




export const getDownloadModuleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof downloadModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof downloadModule>>, TError,{moduleName: string}, TContext> => {

const mutationKey = ['downloadModule'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof downloadModule>>, {moduleName: string}> = (props) => {
          const {moduleName} = props ?? {};

          return  downloadModule(moduleName,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DownloadModuleMutationResult = NonNullable<Awaited<ReturnType<typeof downloadModule>>>

    export type DownloadModuleMutationError = HTTPValidationError

    /**
 * @summary Download Module
 */
export const useDownloadModule = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof downloadModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof downloadModule>>,
        TError,
        {moduleName: string},
        TContext
      > => {
      return useMutation(getDownloadModuleMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Module
 */
export type deleteModuleResponse200 = {
  data: unknown
  status: 200
}

export type deleteModuleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteModuleResponseSuccess = (deleteModuleResponse200) & {
  headers: Headers;
};
export type deleteModuleResponseError = (deleteModuleResponse422) & {
  headers: Headers;
};

export type deleteModuleResponse = (deleteModuleResponseSuccess | deleteModuleResponseError)

export const getDeleteModuleUrl = (moduleName: string,) => {




  return `/modules/${moduleName}`
}

export const deleteModule = async (moduleName: string, options?: RequestInit): Promise<deleteModuleResponse> => {

  const res = await fetch(getDeleteModuleUrl(moduleName),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteModuleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteModuleResponse
}




export const getDeleteModuleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,{moduleName: string}, TContext> => {

const mutationKey = ['deleteModule'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteModule>>, {moduleName: string}> = (props) => {
          const {moduleName} = props ?? {};

          return  deleteModule(moduleName,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteModuleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteModule>>>

    export type DeleteModuleMutationError = HTTPValidationError

    /**
 * @summary Delete Module
 */
export const useDeleteModule = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteModule>>,
        TError,
        {moduleName: string},
        TContext
      > => {
      return useMutation(getDeleteModuleMutationOptions(options), queryClient);
    }
    /**
 * @summary Generate Module
 */
export type generateModuleResponse200 = {
  data: unknown
  status: 200
}

export type generateModuleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type generateModuleResponseSuccess = (generateModuleResponse200) & {
  headers: Headers;
};
export type generateModuleResponseError = (generateModuleResponse422) & {
  headers: Headers;
};

export type generateModuleResponse = (generateModuleResponseSuccess | generateModuleResponseError)

export const getGenerateModuleUrl = (moduleName: string,) => {




  return `/modules/${moduleName}/generate`
}

export const generateModule = async (moduleName: string, options?: RequestInit): Promise<generateModuleResponse> => {

  const res = await fetch(getGenerateModuleUrl(moduleName),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: generateModuleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generateModuleResponse
}




export const getGenerateModuleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generateModule>>, TError,{moduleName: string}, TContext> => {

const mutationKey = ['generateModule'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateModule>>, {moduleName: string}> = (props) => {
          const {moduleName} = props ?? {};

          return  generateModule(moduleName,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GenerateModuleMutationResult = NonNullable<Awaited<ReturnType<typeof generateModule>>>

    export type GenerateModuleMutationError = HTTPValidationError

    /**
 * @summary Generate Module
 */
export const useGenerateModule = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateModule>>,
        TError,
        {moduleName: string},
        TContext
      > => {
      return useMutation(getGenerateModuleMutationOptions(options), queryClient);
    }
