/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";
import type { ModuleSummary, SchemaNode } from "../model";
import { ModuleStatus } from "../model";

export const getGetModulesResponseMock = (): ModuleSummary[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		status: faker.helpers.arrayElement(Object.values(ModuleStatus)),
		revision: faker.string.alpha({ length: { min: 10, max: 20 } }),
	}));

export const getGetSchemaResponseMock = (
	overrideResponse: Partial<Extract<SchemaNode, object>> = {},
): SchemaNode => ({
	kind: faker.string.alpha({ length: { min: 10, max: 20 } }),
	config: faker.helpers.arrayElement([
		faker.helpers.arrayElement([faker.datatype.boolean(), null]),
		undefined,
	]),
	description: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		undefined,
	]),
	mandatory: faker.helpers.arrayElement([
		faker.helpers.arrayElement([faker.datatype.boolean(), null]),
		undefined,
	]),
	default: faker.helpers.arrayElement([
		faker.helpers.arrayElement([null]),
		undefined,
	]),
	type: faker.helpers.arrayElement([
		faker.helpers.arrayElement([null]),
		undefined,
	]),
	children: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			{
				[faker.string.alphanumeric(5)]: {
					kind: faker.string.alpha({ length: { min: 10, max: 20 } }),
					config: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.datatype.boolean(), null]),
						undefined,
					]),
					description: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
					mandatory: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.datatype.boolean(), null]),
						undefined,
					]),
					default: faker.helpers.arrayElement([
						faker.helpers.arrayElement([null]),
						undefined,
					]),
					type: faker.helpers.arrayElement([
						faker.helpers.arrayElement([null]),
						undefined,
					]),
					children: faker.helpers.arrayElement([
						faker.helpers.arrayElement([null]),
						undefined,
					]),
				},
			},
			null,
		]),
		undefined,
	]),
	...overrideResponse,
});
