/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type { HTTPValidationError, ModuleSummary, SchemaNode } from "../model";

/**
 * @summary Get Modules
 */
export type getModulesResponse200 = {
	data: ModuleSummary[];
	status: 200;
};

export type getModulesResponseSuccess = getModulesResponse200 & {
	headers: Headers;
};

export type getModulesResponse = getModulesResponseSuccess;

export const getGetModulesUrl = () => {
	return `/api/v1/modules/`;
};

export const getModules = async (
	options?: RequestInit,
): Promise<getModulesResponse> => {
	const res = await fetch(getGetModulesUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getModulesResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getModulesResponse;
};

export const getGetModulesQueryKey = () => {
	return [`/api/v1/modules/`] as const;
};

export const getGetModulesQueryOptions = <
	TData = Awaited<ReturnType<typeof getModules>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetModulesQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getModules>>> = ({
		signal,
	}) => getModules({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getModules>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetModulesQueryResult = NonNullable<
	Awaited<ReturnType<typeof getModules>>
>;
export type GetModulesQueryError = unknown;

export function useGetModules<
	TData = Awaited<ReturnType<typeof getModules>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getModules>>,
					TError,
					Awaited<ReturnType<typeof getModules>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetModules<
	TData = Awaited<ReturnType<typeof getModules>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getModules>>,
					TError,
					Awaited<ReturnType<typeof getModules>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetModules<
	TData = Awaited<ReturnType<typeof getModules>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Modules
 */

export function useGetModules<
	TData = Awaited<ReturnType<typeof getModules>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetModulesQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete All Modules
 */
export type deleteAllModulesResponse204 = {
	data: void;
	status: 204;
};

export type deleteAllModulesResponseSuccess = deleteAllModulesResponse204 & {
	headers: Headers;
};

export type deleteAllModulesResponse = deleteAllModulesResponseSuccess;

export const getDeleteAllModulesUrl = () => {
	return `/api/v1/modules/`;
};

export const deleteAllModules = async (
	options?: RequestInit,
): Promise<deleteAllModulesResponse> => {
	const res = await fetch(getDeleteAllModulesUrl(), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: deleteAllModulesResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as deleteAllModulesResponse;
};

export const getDeleteAllModulesMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteAllModules>>,
		TError,
		void,
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteAllModules>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["deleteAllModules"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteAllModules>>,
		void
	> = () => {
		return deleteAllModules(fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteAllModulesMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteAllModules>>
>;

export type DeleteAllModulesMutationError = unknown;

/**
 * @summary Delete All Modules
 */
export const useDeleteAllModules = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteAllModules>>,
			TError,
			void,
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteAllModules>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getDeleteAllModulesMutationOptions(options), queryClient);
};
/**
 * @summary Download All Modules
 */
export type downloadAllModulesResponse204 = {
	data: void;
	status: 204;
};

export type downloadAllModulesResponseSuccess =
	downloadAllModulesResponse204 & {
		headers: Headers;
	};

export type downloadAllModulesResponse = downloadAllModulesResponseSuccess;

export const getDownloadAllModulesUrl = () => {
	return `/api/v1/modules/download-all`;
};

export const downloadAllModules = async (
	options?: RequestInit,
): Promise<downloadAllModulesResponse> => {
	const res = await fetch(getDownloadAllModulesUrl(), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: downloadAllModulesResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as downloadAllModulesResponse;
};

export const getDownloadAllModulesMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof downloadAllModules>>,
		TError,
		void,
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof downloadAllModules>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["downloadAllModules"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof downloadAllModules>>,
		void
	> = () => {
		return downloadAllModules(fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DownloadAllModulesMutationResult = NonNullable<
	Awaited<ReturnType<typeof downloadAllModules>>
>;

export type DownloadAllModulesMutationError = unknown;

/**
 * @summary Download All Modules
 */
export const useDownloadAllModules = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof downloadAllModules>>,
			TError,
			void,
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof downloadAllModules>>,
	TError,
	void,
	TContext
> => {
	return useMutation(
		getDownloadAllModulesMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Download Module
 */
export type downloadModuleResponse204 = {
	data: void;
	status: 204;
};

export type downloadModuleResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type downloadModuleResponseSuccess = downloadModuleResponse204 & {
	headers: Headers;
};
export type downloadModuleResponseError = downloadModuleResponse422 & {
	headers: Headers;
};

export type downloadModuleResponse =
	| downloadModuleResponseSuccess
	| downloadModuleResponseError;

export const getDownloadModuleUrl = (moduleName: string) => {
	return `/api/v1/modules/${moduleName}/download`;
};

export const downloadModule = async (
	moduleName: string,
	options?: RequestInit,
): Promise<downloadModuleResponse> => {
	const res = await fetch(getDownloadModuleUrl(moduleName), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: downloadModuleResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as downloadModuleResponse;
};

export const getDownloadModuleMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof downloadModule>>,
		TError,
		{ moduleName: string },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof downloadModule>>,
	TError,
	{ moduleName: string },
	TContext
> => {
	const mutationKey = ["downloadModule"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof downloadModule>>,
		{ moduleName: string }
	> = (props) => {
		const { moduleName } = props ?? {};

		return downloadModule(moduleName, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DownloadModuleMutationResult = NonNullable<
	Awaited<ReturnType<typeof downloadModule>>
>;

export type DownloadModuleMutationError = HTTPValidationError;

/**
 * @summary Download Module
 */
export const useDownloadModule = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof downloadModule>>,
			TError,
			{ moduleName: string },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof downloadModule>>,
	TError,
	{ moduleName: string },
	TContext
> => {
	return useMutation(getDownloadModuleMutationOptions(options), queryClient);
};
/**
 * @summary Delete Module
 */
export type deleteModuleResponse204 = {
	data: void;
	status: 204;
};

export type deleteModuleResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type deleteModuleResponseSuccess = deleteModuleResponse204 & {
	headers: Headers;
};
export type deleteModuleResponseError = deleteModuleResponse422 & {
	headers: Headers;
};

export type deleteModuleResponse =
	| deleteModuleResponseSuccess
	| deleteModuleResponseError;

export const getDeleteModuleUrl = (moduleName: string) => {
	return `/api/v1/modules/${moduleName}`;
};

export const deleteModule = async (
	moduleName: string,
	options?: RequestInit,
): Promise<deleteModuleResponse> => {
	const res = await fetch(getDeleteModuleUrl(moduleName), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: deleteModuleResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as deleteModuleResponse;
};

export const getDeleteModuleMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteModule>>,
		TError,
		{ moduleName: string },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteModule>>,
	TError,
	{ moduleName: string },
	TContext
> => {
	const mutationKey = ["deleteModule"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteModule>>,
		{ moduleName: string }
	> = (props) => {
		const { moduleName } = props ?? {};

		return deleteModule(moduleName, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteModuleMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteModule>>
>;

export type DeleteModuleMutationError = HTTPValidationError;

/**
 * @summary Delete Module
 */
export const useDeleteModule = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteModule>>,
			TError,
			{ moduleName: string },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteModule>>,
	TError,
	{ moduleName: string },
	TContext
> => {
	return useMutation(getDeleteModuleMutationOptions(options), queryClient);
};
/**
 * @summary Get Module Schema
 */
export type getSchemaResponse200 = {
	data: SchemaNode;
	status: 200;
};

export type getSchemaResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getSchemaResponseSuccess = getSchemaResponse200 & {
	headers: Headers;
};
export type getSchemaResponseError = getSchemaResponse422 & {
	headers: Headers;
};

export type getSchemaResponse =
	| getSchemaResponseSuccess
	| getSchemaResponseError;

export const getGetSchemaUrl = (moduleName: string) => {
	return `/api/v1/modules/${moduleName}/schema`;
};

export const getSchema = async (
	moduleName: string,
	options?: RequestInit,
): Promise<getSchemaResponse> => {
	const res = await fetch(getGetSchemaUrl(moduleName), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getSchemaResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getSchemaResponse;
};

export const getGetSchemaQueryKey = (moduleName: string) => {
	return [`/api/v1/modules/${moduleName}/schema`] as const;
};

export const getGetSchemaQueryOptions = <
	TData = Awaited<ReturnType<typeof getSchema>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetSchemaQueryKey(moduleName);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchema>>> = ({
		signal,
	}) => getSchema(moduleName, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!moduleName,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetSchemaQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSchema>>
>;
export type GetSchemaQueryError = HTTPValidationError;

export function useGetSchema<
	TData = Awaited<ReturnType<typeof getSchema>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSchema>>,
					TError,
					Awaited<ReturnType<typeof getSchema>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSchema<
	TData = Awaited<ReturnType<typeof getSchema>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSchema>>,
					TError,
					Awaited<ReturnType<typeof getSchema>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSchema<
	TData = Awaited<ReturnType<typeof getSchema>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Module Schema
 */

export function useGetSchema<
	TData = Awaited<ReturnType<typeof getSchema>>,
	TError = HTTPValidationError,
>(
	moduleName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetSchemaQueryOptions(moduleName, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
