services:
  manager-backend:
    build: .
    container_name: test-manager-backend
    command: pytest -v
    environment:
      - ENVIRONMENT=testing
      - DOWNLOADED_MODULES_PATH=/tmp/downloaded-modules
    networks:
      - test-shared
    depends_on:
      notconf:
        condition: service_healthy

  notconf:
    image: ghcr.io/notconf/notconf:latest
    container_name: notconf
    volumes:
      - ./tests/resources/yang-modules/startup:/yang-modules/startup
    networks:
      - test-shared
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/830"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

networks:
  test-shared:
    name: test-shared
