services:
  manager-backend:
    build: .
    container_name: manager-backend
    user: "${UID}:${GID}"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./resources/yang-modules:/resources/yang-modules
    networks:
      - shared
    
  notconf:
    image: ghcr.io/notconf/notconf-ietf:latest
    container_name: notconf
    ports:
      - "830:830"
      - "80:80"
    networks:
      - shared

networks:
  shared:
    name: shared