services:
  manager-backend:
    build: .
    container_name: manager-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
      - ./app/resources:/resources
      - shared:/shared
    networks:
      - shared
    
  notconf:
    image: ghcr.io/notconf/notconf:latest
    container_name: notconf
    ports:
      - "830:830"
      - "80:80"
    volumes:
      - ./tests/resources/yang-modules:/yang-modules
    networks:
      - shared

networks:
  shared:
    name: shared

volumes:
  shared:
    name: shared