services:
  manager-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
      - ./app/resources:/resources
      - shared:/shared
    networks:
      - shared
    command: fastapi dev --host 0.0.0.0 app/main.py

  notconf:
    image: ghcr.io/notconf/notconf:latest
    container_name: notconf
    ports:
      - "830:830"
    volumes:
      - ./app/resources/yang-modules/startup:/yang-modules/startup
    networks:
      - shared
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/830" ]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

networks:
  shared:
    name: shared

volumes:
  shared:
    name: shared
