services:
  manager-backend:
    build: .
    container_name: test-manager-backend
    command: pytest
    environment:
      - ENVIRONMENT=testing
      - DOWNLOADED_MODULES_PATH=/tmp/downloaded-modules
    networks:
      - test-shared
    depends_on:
      notconf:
        condition: service_started

  notconf:
    image: ghcr.io/notconf/notconf:latest
    container_name: notconf
    volumes:
      - ./tests/resources/yang-modules/startup:/yang-modules/startup
    networks:
      - test-shared

networks:
  test-shared:
    name: test-shared
