# .github/workflows/tests.yml
name: Backend tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: manager-backend

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv sync
      - run: uv run ruff check .
      - run: uv run ruff format --check .
      - run: uv run basedpyright

  test:
    needs: static-analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: manager-backend

    steps:
      - uses: actions/checkout@v4

      - run: docker compose -f docker-compose.yml -f docker-compose.test.yml -p test up --build --exit-code-from manager-backend

      - if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml -p test down
