/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Connection {
  host?: string;
  port?: number;
  user_name?: string;
  password?: string;
}
