/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DataStore = (typeof DataStore)[keyof typeof DataStore];

export const DataStore = {
	startup: "startup",
	candidate: "candidate",
	running: "running",
} as const;
