/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ModuleStatus = typeof ModuleStatus[keyof typeof ModuleStatus];


export const ModuleStatus = {
  remote: 'remote',
  local: 'local',
} as const;
