/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModuleStatus } from "./moduleStatus";

export interface ModuleSummary {
	name: string;
	status: ModuleStatus;
	revision?: string;
}
