/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModuleStatus } from './moduleStatus';

export interface Module {
  name: string;
  readonly status: ModuleStatus;
  readonly yang_module_path: string;
  readonly generated_model_path: string;
  readonly exists: boolean;
}
