/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaNode } from "./schemaNode";

export type SchemaNodeChildren = { [key: string]: SchemaNode } | null;
