/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  SchemaNode
} from '../model';





/**
 * @summary Get Schema
 */
export type getSchemaResponse200 = {
  data: SchemaNode
  status: 200
}

export type getSchemaResponseSuccess = (getSchemaResponse200) & {
  headers: Headers;
};
;

export type getSchemaResponse = (getSchemaResponseSuccess)

export const getGetSchemaUrl = () => {




  return `/schema/`
}

export const getSchema = async ( options?: RequestInit): Promise<getSchemaResponse> => {

  const res = await fetch(getGetSchemaUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSchemaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSchemaResponse
}





export const getGetSchemaQueryKey = () => {
    return [
    `/schema/`
    ] as const;
    }


export const getGetSchemaQueryOptions = <TData = Awaited<ReturnType<typeof getSchema>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSchemaQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchema>>> = ({ signal }) => getSchema({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof getSchema>>>
export type GetSchemaQueryError = unknown


export function useGetSchema<TData = Awaited<ReturnType<typeof getSchema>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchema>>,
          TError,
          Awaited<ReturnType<typeof getSchema>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchema<TData = Awaited<ReturnType<typeof getSchema>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchema>>,
          TError,
          Awaited<ReturnType<typeof getSchema>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchema<TData = Awaited<ReturnType<typeof getSchema>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Schema
 */

export function useGetSchema<TData = Awaited<ReturnType<typeof getSchema>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchema>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSchemaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Module Schema
 */
export type getModuleSchemaResponse200 = {
  data: SchemaNode
  status: 200
}

export type getModuleSchemaResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getModuleSchemaResponseSuccess = (getModuleSchemaResponse200) & {
  headers: Headers;
};
export type getModuleSchemaResponseError = (getModuleSchemaResponse422) & {
  headers: Headers;
};

export type getModuleSchemaResponse = (getModuleSchemaResponseSuccess | getModuleSchemaResponseError)

export const getGetModuleSchemaUrl = (moduleName: string,) => {




  return `/schema/${moduleName}`
}

export const getModuleSchema = async (moduleName: string, options?: RequestInit): Promise<getModuleSchemaResponse> => {

  const res = await fetch(getGetModuleSchemaUrl(moduleName),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getModuleSchemaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getModuleSchemaResponse
}





export const getGetModuleSchemaQueryKey = (moduleName: string,) => {
    return [
    `/schema/${moduleName}`
    ] as const;
    }


export const getGetModuleSchemaQueryOptions = <TData = Awaited<ReturnType<typeof getModuleSchema>>, TError = HTTPValidationError>(moduleName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSchema>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModuleSchemaQueryKey(moduleName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleSchema>>> = ({ signal }) => getModuleSchema(moduleName, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(moduleName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModuleSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModuleSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof getModuleSchema>>>
export type GetModuleSchemaQueryError = HTTPValidationError


export function useGetModuleSchema<TData = Awaited<ReturnType<typeof getModuleSchema>>, TError = HTTPValidationError>(
 moduleName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleSchema>>,
          TError,
          Awaited<ReturnType<typeof getModuleSchema>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleSchema<TData = Awaited<ReturnType<typeof getModuleSchema>>, TError = HTTPValidationError>(
 moduleName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleSchema>>,
          TError,
          Awaited<ReturnType<typeof getModuleSchema>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleSchema<TData = Awaited<ReturnType<typeof getModuleSchema>>, TError = HTTPValidationError>(
 moduleName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSchema>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Module Schema
 */

export function useGetModuleSchema<TData = Awaited<ReturnType<typeof getModuleSchema>>, TError = HTTPValidationError>(
 moduleName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSchema>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModuleSchemaQueryOptions(moduleName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




