FROM node:24-alpine

WORKDIR /app
RUN chown node:node /app
COPY --chown=node:node package.json package-lock.json ./

USER node
RUN npm ci

COPY --chown=node:node . .

EXPOSE 5173
CMD ["npm", "run", "dev-api", "--", "--host"]
