services:
  manager-frontend:
    build: .
    container_name: manager-frontend
    user: "${UID:-0}:${GID:-0}"
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - shared-spec:/shared
    networks:
      - shared

networks:
  shared:
    name: shared

volumes:
  shared-spec:
