/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Connection,
  HTTPValidationError
} from '../model';





/**
 * @summary Connect
 */
export type connectConnectPostResponse200 = {
  data: string[]
  status: 200
}

export type connectConnectPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type connectConnectPostResponseSuccess = (connectConnectPostResponse200) & {
  headers: Headers;
};
export type connectConnectPostResponseError = (connectConnectPostResponse422) & {
  headers: Headers;
};

export type connectConnectPostResponse = (connectConnectPostResponseSuccess | connectConnectPostResponseError)

export const getConnectConnectPostUrl = () => {




  return `/connect`
}

export const connectConnectPost = async (connection: Connection, options?: RequestInit): Promise<connectConnectPostResponse> => {

  const res = await fetch(getConnectConnectPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      connection,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: connectConnectPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as connectConnectPostResponse
}




export const getConnectConnectPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectConnectPost>>, TError,{data: Connection}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof connectConnectPost>>, TError,{data: Connection}, TContext> => {

const mutationKey = ['connectConnectPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connectConnectPost>>, {data: Connection}> = (props) => {
          const {data} = props ?? {};

          return  connectConnectPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectConnectPostMutationResult = NonNullable<Awaited<ReturnType<typeof connectConnectPost>>>
    export type ConnectConnectPostMutationBody = Connection
    export type ConnectConnectPostMutationError = HTTPValidationError

    /**
 * @summary Connect
 */
export const useConnectConnectPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectConnectPost>>, TError,{data: Connection}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connectConnectPost>>,
        TError,
        {data: Connection},
        TContext
      > => {
      return useMutation(getConnectConnectPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Disconnect
 */
export type disconnectConnectDeleteResponse200 = {
  data: string[]
  status: 200
}

export type disconnectConnectDeleteResponseSuccess = (disconnectConnectDeleteResponse200) & {
  headers: Headers;
};
;

export type disconnectConnectDeleteResponse = (disconnectConnectDeleteResponseSuccess)

export const getDisconnectConnectDeleteUrl = () => {




  return `/connect`
}

export const disconnectConnectDelete = async ( options?: RequestInit): Promise<disconnectConnectDeleteResponse> => {

  const res = await fetch(getDisconnectConnectDeleteUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: disconnectConnectDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as disconnectConnectDeleteResponse
}




export const getDisconnectConnectDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnectConnectDelete>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof disconnectConnectDelete>>, TError,void, TContext> => {

const mutationKey = ['disconnectConnectDelete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disconnectConnectDelete>>, void> = () => {


          return  disconnectConnectDelete(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DisconnectConnectDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof disconnectConnectDelete>>>

    export type DisconnectConnectDeleteMutationError = unknown

    /**
 * @summary Disconnect
 */
export const useDisconnectConnectDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnectConnectDelete>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disconnectConnectDelete>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDisconnectConnectDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get
 */
export type getNetconfGetPostResponse200 = {
  data: unknown
  status: 200
}

export type getNetconfGetPostResponseSuccess = (getNetconfGetPostResponse200) & {
  headers: Headers;
};
;

export type getNetconfGetPostResponse = (getNetconfGetPostResponseSuccess)

export const getGetNetconfGetPostUrl = () => {




  return `/netconf/get`
}

export const getNetconfGetPost = async ( options?: RequestInit): Promise<getNetconfGetPostResponse> => {

  const res = await fetch(getGetNetconfGetPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNetconfGetPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNetconfGetPostResponse
}




export const getGetNetconfGetPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getNetconfGetPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof getNetconfGetPost>>, TError,void, TContext> => {

const mutationKey = ['getNetconfGetPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getNetconfGetPost>>, void> = () => {


          return  getNetconfGetPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetNetconfGetPostMutationResult = NonNullable<Awaited<ReturnType<typeof getNetconfGetPost>>>

    export type GetNetconfGetPostMutationError = unknown

    /**
 * @summary Get
 */
export const useGetNetconfGetPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getNetconfGetPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getNetconfGetPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetNetconfGetPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Config
 */
export type getConfigNetconfGetConfigPostResponse200 = {
  data: unknown
  status: 200
}

export type getConfigNetconfGetConfigPostResponseSuccess = (getConfigNetconfGetConfigPostResponse200) & {
  headers: Headers;
};
;

export type getConfigNetconfGetConfigPostResponse = (getConfigNetconfGetConfigPostResponseSuccess)

export const getGetConfigNetconfGetConfigPostUrl = () => {




  return `/netconf/get-config`
}

export const getConfigNetconfGetConfigPost = async ( options?: RequestInit): Promise<getConfigNetconfGetConfigPostResponse> => {

  const res = await fetch(getGetConfigNetconfGetConfigPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getConfigNetconfGetConfigPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getConfigNetconfGetConfigPostResponse
}




export const getGetConfigNetconfGetConfigPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getConfigNetconfGetConfigPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof getConfigNetconfGetConfigPost>>, TError,void, TContext> => {

const mutationKey = ['getConfigNetconfGetConfigPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getConfigNetconfGetConfigPost>>, void> = () => {


          return  getConfigNetconfGetConfigPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetConfigNetconfGetConfigPostMutationResult = NonNullable<Awaited<ReturnType<typeof getConfigNetconfGetConfigPost>>>

    export type GetConfigNetconfGetConfigPostMutationError = unknown

    /**
 * @summary Get Config
 */
export const useGetConfigNetconfGetConfigPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getConfigNetconfGetConfigPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getConfigNetconfGetConfigPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetConfigNetconfGetConfigPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Schemas
 */
export type getSchemasNetconfGetSchemasGetResponse200 = {
  data: string[]
  status: 200
}

export type getSchemasNetconfGetSchemasGetResponseSuccess = (getSchemasNetconfGetSchemasGetResponse200) & {
  headers: Headers;
};
;

export type getSchemasNetconfGetSchemasGetResponse = (getSchemasNetconfGetSchemasGetResponseSuccess)

export const getGetSchemasNetconfGetSchemasGetUrl = () => {




  return `/netconf/get-schemas`
}

export const getSchemasNetconfGetSchemasGet = async ( options?: RequestInit): Promise<getSchemasNetconfGetSchemasGetResponse> => {

  const res = await fetch(getGetSchemasNetconfGetSchemasGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSchemasNetconfGetSchemasGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSchemasNetconfGetSchemasGetResponse
}





export const getGetSchemasNetconfGetSchemasGetQueryKey = () => {
    return [
    `/netconf/get-schemas`
    ] as const;
    }


export const getGetSchemasNetconfGetSchemasGetQueryOptions = <TData = Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSchemasNetconfGetSchemasGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>> = ({ signal }) => getSchemasNetconfGetSchemasGet({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSchemasNetconfGetSchemasGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>>
export type GetSchemasNetconfGetSchemasGetQueryError = unknown


export function useGetSchemasNetconfGetSchemasGet<TData = Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>,
          TError,
          Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchemasNetconfGetSchemasGet<TData = Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>,
          TError,
          Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchemasNetconfGetSchemasGet<TData = Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Schemas
 */

export function useGetSchemasNetconfGetSchemasGet<TData = Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemasNetconfGetSchemasGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSchemasNetconfGetSchemasGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Schema
 */
export type getSchemaNetconfGetSchemaSchemaNameGetResponse200 = {
  data: unknown
  status: 200
}

export type getSchemaNetconfGetSchemaSchemaNameGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getSchemaNetconfGetSchemaSchemaNameGetResponseSuccess = (getSchemaNetconfGetSchemaSchemaNameGetResponse200) & {
  headers: Headers;
};
export type getSchemaNetconfGetSchemaSchemaNameGetResponseError = (getSchemaNetconfGetSchemaSchemaNameGetResponse422) & {
  headers: Headers;
};

export type getSchemaNetconfGetSchemaSchemaNameGetResponse = (getSchemaNetconfGetSchemaSchemaNameGetResponseSuccess | getSchemaNetconfGetSchemaSchemaNameGetResponseError)

export const getGetSchemaNetconfGetSchemaSchemaNameGetUrl = (schemaName: string,) => {




  return `/netconf/get-schema/${schemaName}`
}

export const getSchemaNetconfGetSchemaSchemaNameGet = async (schemaName: string, options?: RequestInit): Promise<getSchemaNetconfGetSchemaSchemaNameGetResponse> => {

  const res = await fetch(getGetSchemaNetconfGetSchemaSchemaNameGetUrl(schemaName),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSchemaNetconfGetSchemaSchemaNameGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSchemaNetconfGetSchemaSchemaNameGetResponse
}





export const getGetSchemaNetconfGetSchemaSchemaNameGetQueryKey = (schemaName: string,) => {
    return [
    `/netconf/get-schema/${schemaName}`
    ] as const;
    }


export const getGetSchemaNetconfGetSchemaSchemaNameGetQueryOptions = <TData = Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError = HTTPValidationError>(schemaName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSchemaNetconfGetSchemaSchemaNameGetQueryKey(schemaName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>> = ({ signal }) => getSchemaNetconfGetSchemaSchemaNameGet(schemaName, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(schemaName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSchemaNetconfGetSchemaSchemaNameGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>>
export type GetSchemaNetconfGetSchemaSchemaNameGetQueryError = HTTPValidationError


export function useGetSchemaNetconfGetSchemaSchemaNameGet<TData = Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError = HTTPValidationError>(
 schemaName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>,
          TError,
          Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchemaNetconfGetSchemaSchemaNameGet<TData = Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError = HTTPValidationError>(
 schemaName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>,
          TError,
          Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchemaNetconfGetSchemaSchemaNameGet<TData = Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError = HTTPValidationError>(
 schemaName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Schema
 */

export function useGetSchemaNetconfGetSchemaSchemaNameGet<TData = Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError = HTTPValidationError>(
 schemaName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchemaNetconfGetSchemaSchemaNameGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSchemaNetconfGetSchemaSchemaNameGetQueryOptions(schemaName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Dispatch
 */
export type dispatchNetconfDispatchPostResponse200 = {
  data: unknown
  status: 200
}

export type dispatchNetconfDispatchPostResponseSuccess = (dispatchNetconfDispatchPostResponse200) & {
  headers: Headers;
};
;

export type dispatchNetconfDispatchPostResponse = (dispatchNetconfDispatchPostResponseSuccess)

export const getDispatchNetconfDispatchPostUrl = () => {




  return `/netconf/dispatch`
}

export const dispatchNetconfDispatchPost = async ( options?: RequestInit): Promise<dispatchNetconfDispatchPostResponse> => {

  const res = await fetch(getDispatchNetconfDispatchPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dispatchNetconfDispatchPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as dispatchNetconfDispatchPostResponse
}




export const getDispatchNetconfDispatchPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchNetconfDispatchPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof dispatchNetconfDispatchPost>>, TError,void, TContext> => {

const mutationKey = ['dispatchNetconfDispatchPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dispatchNetconfDispatchPost>>, void> = () => {


          return  dispatchNetconfDispatchPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DispatchNetconfDispatchPostMutationResult = NonNullable<Awaited<ReturnType<typeof dispatchNetconfDispatchPost>>>

    export type DispatchNetconfDispatchPostMutationError = unknown

    /**
 * @summary Dispatch
 */
export const useDispatchNetconfDispatchPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dispatchNetconfDispatchPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dispatchNetconfDispatchPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDispatchNetconfDispatchPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Edit Config
 */
export type editConfigNetconfEditConfigPostResponse200 = {
  data: unknown
  status: 200
}

export type editConfigNetconfEditConfigPostResponseSuccess = (editConfigNetconfEditConfigPostResponse200) & {
  headers: Headers;
};
;

export type editConfigNetconfEditConfigPostResponse = (editConfigNetconfEditConfigPostResponseSuccess)

export const getEditConfigNetconfEditConfigPostUrl = () => {




  return `/netconf/edit-config`
}

export const editConfigNetconfEditConfigPost = async ( options?: RequestInit): Promise<editConfigNetconfEditConfigPostResponse> => {

  const res = await fetch(getEditConfigNetconfEditConfigPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: editConfigNetconfEditConfigPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as editConfigNetconfEditConfigPostResponse
}




export const getEditConfigNetconfEditConfigPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editConfigNetconfEditConfigPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof editConfigNetconfEditConfigPost>>, TError,void, TContext> => {

const mutationKey = ['editConfigNetconfEditConfigPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editConfigNetconfEditConfigPost>>, void> = () => {


          return  editConfigNetconfEditConfigPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditConfigNetconfEditConfigPostMutationResult = NonNullable<Awaited<ReturnType<typeof editConfigNetconfEditConfigPost>>>

    export type EditConfigNetconfEditConfigPostMutationError = unknown

    /**
 * @summary Edit Config
 */
export const useEditConfigNetconfEditConfigPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editConfigNetconfEditConfigPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editConfigNetconfEditConfigPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getEditConfigNetconfEditConfigPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Copy Config
 */
export type copyConfigNetconfCopyConfigPostResponse200 = {
  data: unknown
  status: 200
}

export type copyConfigNetconfCopyConfigPostResponseSuccess = (copyConfigNetconfCopyConfigPostResponse200) & {
  headers: Headers;
};
;

export type copyConfigNetconfCopyConfigPostResponse = (copyConfigNetconfCopyConfigPostResponseSuccess)

export const getCopyConfigNetconfCopyConfigPostUrl = () => {




  return `/netconf/copy-config`
}

export const copyConfigNetconfCopyConfigPost = async ( options?: RequestInit): Promise<copyConfigNetconfCopyConfigPostResponse> => {

  const res = await fetch(getCopyConfigNetconfCopyConfigPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: copyConfigNetconfCopyConfigPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as copyConfigNetconfCopyConfigPostResponse
}




export const getCopyConfigNetconfCopyConfigPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof copyConfigNetconfCopyConfigPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof copyConfigNetconfCopyConfigPost>>, TError,void, TContext> => {

const mutationKey = ['copyConfigNetconfCopyConfigPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof copyConfigNetconfCopyConfigPost>>, void> = () => {


          return  copyConfigNetconfCopyConfigPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CopyConfigNetconfCopyConfigPostMutationResult = NonNullable<Awaited<ReturnType<typeof copyConfigNetconfCopyConfigPost>>>

    export type CopyConfigNetconfCopyConfigPostMutationError = unknown

    /**
 * @summary Copy Config
 */
export const useCopyConfigNetconfCopyConfigPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof copyConfigNetconfCopyConfigPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof copyConfigNetconfCopyConfigPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCopyConfigNetconfCopyConfigPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Validate
 */
export type validateNetconfValidatePostResponse200 = {
  data: unknown
  status: 200
}

export type validateNetconfValidatePostResponseSuccess = (validateNetconfValidatePostResponse200) & {
  headers: Headers;
};
;

export type validateNetconfValidatePostResponse = (validateNetconfValidatePostResponseSuccess)

export const getValidateNetconfValidatePostUrl = () => {




  return `/netconf/validate`
}

export const validateNetconfValidatePost = async ( options?: RequestInit): Promise<validateNetconfValidatePostResponse> => {

  const res = await fetch(getValidateNetconfValidatePostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: validateNetconfValidatePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as validateNetconfValidatePostResponse
}




export const getValidateNetconfValidatePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateNetconfValidatePost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof validateNetconfValidatePost>>, TError,void, TContext> => {

const mutationKey = ['validateNetconfValidatePost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof validateNetconfValidatePost>>, void> = () => {


          return  validateNetconfValidatePost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ValidateNetconfValidatePostMutationResult = NonNullable<Awaited<ReturnType<typeof validateNetconfValidatePost>>>

    export type ValidateNetconfValidatePostMutationError = unknown

    /**
 * @summary Validate
 */
export const useValidateNetconfValidatePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateNetconfValidatePost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof validateNetconfValidatePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getValidateNetconfValidatePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Commit
 */
export type commitNetconfCommitPostResponse200 = {
  data: unknown
  status: 200
}

export type commitNetconfCommitPostResponseSuccess = (commitNetconfCommitPostResponse200) & {
  headers: Headers;
};
;

export type commitNetconfCommitPostResponse = (commitNetconfCommitPostResponseSuccess)

export const getCommitNetconfCommitPostUrl = () => {




  return `/netconf/commit`
}

export const commitNetconfCommitPost = async ( options?: RequestInit): Promise<commitNetconfCommitPostResponse> => {

  const res = await fetch(getCommitNetconfCommitPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commitNetconfCommitPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commitNetconfCommitPostResponse
}




export const getCommitNetconfCommitPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commitNetconfCommitPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commitNetconfCommitPost>>, TError,void, TContext> => {

const mutationKey = ['commitNetconfCommitPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commitNetconfCommitPost>>, void> = () => {


          return  commitNetconfCommitPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommitNetconfCommitPostMutationResult = NonNullable<Awaited<ReturnType<typeof commitNetconfCommitPost>>>

    export type CommitNetconfCommitPostMutationError = unknown

    /**
 * @summary Commit
 */
export const useCommitNetconfCommitPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commitNetconfCommitPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof commitNetconfCommitPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCommitNetconfCommitPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Discard Changes
 */
export type discardChangesNetconfDiscardChangesPostResponse200 = {
  data: unknown
  status: 200
}

export type discardChangesNetconfDiscardChangesPostResponseSuccess = (discardChangesNetconfDiscardChangesPostResponse200) & {
  headers: Headers;
};
;

export type discardChangesNetconfDiscardChangesPostResponse = (discardChangesNetconfDiscardChangesPostResponseSuccess)

export const getDiscardChangesNetconfDiscardChangesPostUrl = () => {




  return `/netconf/discard-changes`
}

export const discardChangesNetconfDiscardChangesPost = async ( options?: RequestInit): Promise<discardChangesNetconfDiscardChangesPostResponse> => {

  const res = await fetch(getDiscardChangesNetconfDiscardChangesPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: discardChangesNetconfDiscardChangesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as discardChangesNetconfDiscardChangesPostResponse
}




export const getDiscardChangesNetconfDiscardChangesPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof discardChangesNetconfDiscardChangesPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof discardChangesNetconfDiscardChangesPost>>, TError,void, TContext> => {

const mutationKey = ['discardChangesNetconfDiscardChangesPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof discardChangesNetconfDiscardChangesPost>>, void> = () => {


          return  discardChangesNetconfDiscardChangesPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DiscardChangesNetconfDiscardChangesPostMutationResult = NonNullable<Awaited<ReturnType<typeof discardChangesNetconfDiscardChangesPost>>>

    export type DiscardChangesNetconfDiscardChangesPostMutationError = unknown

    /**
 * @summary Discard Changes
 */
export const useDiscardChangesNetconfDiscardChangesPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof discardChangesNetconfDiscardChangesPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof discardChangesNetconfDiscardChangesPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDiscardChangesNetconfDiscardChangesPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Cancel Commit
 */
export type cancelCommitNetconfCancelCommitPostResponse200 = {
  data: unknown
  status: 200
}

export type cancelCommitNetconfCancelCommitPostResponseSuccess = (cancelCommitNetconfCancelCommitPostResponse200) & {
  headers: Headers;
};
;

export type cancelCommitNetconfCancelCommitPostResponse = (cancelCommitNetconfCancelCommitPostResponseSuccess)

export const getCancelCommitNetconfCancelCommitPostUrl = () => {




  return `/netconf/cancel-commit`
}

export const cancelCommitNetconfCancelCommitPost = async ( options?: RequestInit): Promise<cancelCommitNetconfCancelCommitPostResponse> => {

  const res = await fetch(getCancelCommitNetconfCancelCommitPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: cancelCommitNetconfCancelCommitPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as cancelCommitNetconfCancelCommitPostResponse
}




export const getCancelCommitNetconfCancelCommitPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelCommitNetconfCancelCommitPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof cancelCommitNetconfCancelCommitPost>>, TError,void, TContext> => {

const mutationKey = ['cancelCommitNetconfCancelCommitPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelCommitNetconfCancelCommitPost>>, void> = () => {


          return  cancelCommitNetconfCancelCommitPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CancelCommitNetconfCancelCommitPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelCommitNetconfCancelCommitPost>>>

    export type CancelCommitNetconfCancelCommitPostMutationError = unknown

    /**
 * @summary Cancel Commit
 */
export const useCancelCommitNetconfCancelCommitPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelCommitNetconfCancelCommitPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelCommitNetconfCancelCommitPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCancelCommitNetconfCancelCommitPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Config
 */
export type deleteConfigNetconfDeleteConfigPostResponse200 = {
  data: unknown
  status: 200
}

export type deleteConfigNetconfDeleteConfigPostResponseSuccess = (deleteConfigNetconfDeleteConfigPostResponse200) & {
  headers: Headers;
};
;

export type deleteConfigNetconfDeleteConfigPostResponse = (deleteConfigNetconfDeleteConfigPostResponseSuccess)

export const getDeleteConfigNetconfDeleteConfigPostUrl = () => {




  return `/netconf/delete-config`
}

export const deleteConfigNetconfDeleteConfigPost = async ( options?: RequestInit): Promise<deleteConfigNetconfDeleteConfigPostResponse> => {

  const res = await fetch(getDeleteConfigNetconfDeleteConfigPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteConfigNetconfDeleteConfigPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteConfigNetconfDeleteConfigPostResponse
}




export const getDeleteConfigNetconfDeleteConfigPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteConfigNetconfDeleteConfigPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteConfigNetconfDeleteConfigPost>>, TError,void, TContext> => {

const mutationKey = ['deleteConfigNetconfDeleteConfigPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteConfigNetconfDeleteConfigPost>>, void> = () => {


          return  deleteConfigNetconfDeleteConfigPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteConfigNetconfDeleteConfigPostMutationResult = NonNullable<Awaited<ReturnType<typeof deleteConfigNetconfDeleteConfigPost>>>

    export type DeleteConfigNetconfDeleteConfigPostMutationError = unknown

    /**
 * @summary Delete Config
 */
export const useDeleteConfigNetconfDeleteConfigPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteConfigNetconfDeleteConfigPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteConfigNetconfDeleteConfigPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteConfigNetconfDeleteConfigPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Lock
 */
export type lockNetconfLockPostResponse200 = {
  data: unknown
  status: 200
}

export type lockNetconfLockPostResponseSuccess = (lockNetconfLockPostResponse200) & {
  headers: Headers;
};
;

export type lockNetconfLockPostResponse = (lockNetconfLockPostResponseSuccess)

export const getLockNetconfLockPostUrl = () => {




  return `/netconf/lock`
}

export const lockNetconfLockPost = async ( options?: RequestInit): Promise<lockNetconfLockPostResponse> => {

  const res = await fetch(getLockNetconfLockPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: lockNetconfLockPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as lockNetconfLockPostResponse
}




export const getLockNetconfLockPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lockNetconfLockPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof lockNetconfLockPost>>, TError,void, TContext> => {

const mutationKey = ['lockNetconfLockPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lockNetconfLockPost>>, void> = () => {


          return  lockNetconfLockPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LockNetconfLockPostMutationResult = NonNullable<Awaited<ReturnType<typeof lockNetconfLockPost>>>

    export type LockNetconfLockPostMutationError = unknown

    /**
 * @summary Lock
 */
export const useLockNetconfLockPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lockNetconfLockPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lockNetconfLockPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLockNetconfLockPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Unlock
 */
export type unlockNetconfUnlockPostResponse200 = {
  data: unknown
  status: 200
}

export type unlockNetconfUnlockPostResponseSuccess = (unlockNetconfUnlockPostResponse200) & {
  headers: Headers;
};
;

export type unlockNetconfUnlockPostResponse = (unlockNetconfUnlockPostResponseSuccess)

export const getUnlockNetconfUnlockPostUrl = () => {




  return `/netconf/unlock`
}

export const unlockNetconfUnlockPost = async ( options?: RequestInit): Promise<unlockNetconfUnlockPostResponse> => {

  const res = await fetch(getUnlockNetconfUnlockPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: unlockNetconfUnlockPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unlockNetconfUnlockPostResponse
}




export const getUnlockNetconfUnlockPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlockNetconfUnlockPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof unlockNetconfUnlockPost>>, TError,void, TContext> => {

const mutationKey = ['unlockNetconfUnlockPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unlockNetconfUnlockPost>>, void> = () => {


          return  unlockNetconfUnlockPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnlockNetconfUnlockPostMutationResult = NonNullable<Awaited<ReturnType<typeof unlockNetconfUnlockPost>>>

    export type UnlockNetconfUnlockPostMutationError = unknown

    /**
 * @summary Unlock
 */
export const useUnlockNetconfUnlockPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlockNetconfUnlockPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unlockNetconfUnlockPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUnlockNetconfUnlockPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Create Subscription
 */
export type createSubscriptionNetconfCreateSubscriptionPostResponse200 = {
  data: unknown
  status: 200
}

export type createSubscriptionNetconfCreateSubscriptionPostResponseSuccess = (createSubscriptionNetconfCreateSubscriptionPostResponse200) & {
  headers: Headers;
};
;

export type createSubscriptionNetconfCreateSubscriptionPostResponse = (createSubscriptionNetconfCreateSubscriptionPostResponseSuccess)

export const getCreateSubscriptionNetconfCreateSubscriptionPostUrl = () => {




  return `/netconf/create-subscription`
}

export const createSubscriptionNetconfCreateSubscriptionPost = async ( options?: RequestInit): Promise<createSubscriptionNetconfCreateSubscriptionPostResponse> => {

  const res = await fetch(getCreateSubscriptionNetconfCreateSubscriptionPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSubscriptionNetconfCreateSubscriptionPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSubscriptionNetconfCreateSubscriptionPostResponse
}




export const getCreateSubscriptionNetconfCreateSubscriptionPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSubscriptionNetconfCreateSubscriptionPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createSubscriptionNetconfCreateSubscriptionPost>>, TError,void, TContext> => {

const mutationKey = ['createSubscriptionNetconfCreateSubscriptionPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSubscriptionNetconfCreateSubscriptionPost>>, void> = () => {


          return  createSubscriptionNetconfCreateSubscriptionPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSubscriptionNetconfCreateSubscriptionPostMutationResult = NonNullable<Awaited<ReturnType<typeof createSubscriptionNetconfCreateSubscriptionPost>>>

    export type CreateSubscriptionNetconfCreateSubscriptionPostMutationError = unknown

    /**
 * @summary Create Subscription
 */
export const useCreateSubscriptionNetconfCreateSubscriptionPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSubscriptionNetconfCreateSubscriptionPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSubscriptionNetconfCreateSubscriptionPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCreateSubscriptionNetconfCreateSubscriptionPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Close Session
 */
export type closeSessionNetconfCloseSessionPostResponse200 = {
  data: unknown
  status: 200
}

export type closeSessionNetconfCloseSessionPostResponseSuccess = (closeSessionNetconfCloseSessionPostResponse200) & {
  headers: Headers;
};
;

export type closeSessionNetconfCloseSessionPostResponse = (closeSessionNetconfCloseSessionPostResponseSuccess)

export const getCloseSessionNetconfCloseSessionPostUrl = () => {




  return `/netconf/close-session`
}

export const closeSessionNetconfCloseSessionPost = async ( options?: RequestInit): Promise<closeSessionNetconfCloseSessionPostResponse> => {

  const res = await fetch(getCloseSessionNetconfCloseSessionPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: closeSessionNetconfCloseSessionPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as closeSessionNetconfCloseSessionPostResponse
}




export const getCloseSessionNetconfCloseSessionPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeSessionNetconfCloseSessionPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof closeSessionNetconfCloseSessionPost>>, TError,void, TContext> => {

const mutationKey = ['closeSessionNetconfCloseSessionPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closeSessionNetconfCloseSessionPost>>, void> = () => {


          return  closeSessionNetconfCloseSessionPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CloseSessionNetconfCloseSessionPostMutationResult = NonNullable<Awaited<ReturnType<typeof closeSessionNetconfCloseSessionPost>>>

    export type CloseSessionNetconfCloseSessionPostMutationError = unknown

    /**
 * @summary Close Session
 */
export const useCloseSessionNetconfCloseSessionPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeSessionNetconfCloseSessionPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closeSessionNetconfCloseSessionPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCloseSessionNetconfCloseSessionPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Kill Session
 */
export type killSessionNetconfKillSessionPostResponse200 = {
  data: unknown
  status: 200
}

export type killSessionNetconfKillSessionPostResponseSuccess = (killSessionNetconfKillSessionPostResponse200) & {
  headers: Headers;
};
;

export type killSessionNetconfKillSessionPostResponse = (killSessionNetconfKillSessionPostResponseSuccess)

export const getKillSessionNetconfKillSessionPostUrl = () => {




  return `/netconf/kill-session`
}

export const killSessionNetconfKillSessionPost = async ( options?: RequestInit): Promise<killSessionNetconfKillSessionPostResponse> => {

  const res = await fetch(getKillSessionNetconfKillSessionPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: killSessionNetconfKillSessionPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as killSessionNetconfKillSessionPostResponse
}




export const getKillSessionNetconfKillSessionPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof killSessionNetconfKillSessionPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof killSessionNetconfKillSessionPost>>, TError,void, TContext> => {

const mutationKey = ['killSessionNetconfKillSessionPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof killSessionNetconfKillSessionPost>>, void> = () => {


          return  killSessionNetconfKillSessionPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type KillSessionNetconfKillSessionPostMutationResult = NonNullable<Awaited<ReturnType<typeof killSessionNetconfKillSessionPost>>>

    export type KillSessionNetconfKillSessionPostMutationError = unknown

    /**
 * @summary Kill Session
 */
export const useKillSessionNetconfKillSessionPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof killSessionNetconfKillSessionPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof killSessionNetconfKillSessionPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getKillSessionNetconfKillSessionPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Poweroff Machine
 */
export type poweroffMachineNetconfPoweroffMachinePostResponse200 = {
  data: unknown
  status: 200
}

export type poweroffMachineNetconfPoweroffMachinePostResponseSuccess = (poweroffMachineNetconfPoweroffMachinePostResponse200) & {
  headers: Headers;
};
;

export type poweroffMachineNetconfPoweroffMachinePostResponse = (poweroffMachineNetconfPoweroffMachinePostResponseSuccess)

export const getPoweroffMachineNetconfPoweroffMachinePostUrl = () => {




  return `/netconf/poweroff-machine`
}

export const poweroffMachineNetconfPoweroffMachinePost = async ( options?: RequestInit): Promise<poweroffMachineNetconfPoweroffMachinePostResponse> => {

  const res = await fetch(getPoweroffMachineNetconfPoweroffMachinePostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: poweroffMachineNetconfPoweroffMachinePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as poweroffMachineNetconfPoweroffMachinePostResponse
}




export const getPoweroffMachineNetconfPoweroffMachinePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof poweroffMachineNetconfPoweroffMachinePost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof poweroffMachineNetconfPoweroffMachinePost>>, TError,void, TContext> => {

const mutationKey = ['poweroffMachineNetconfPoweroffMachinePost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof poweroffMachineNetconfPoweroffMachinePost>>, void> = () => {


          return  poweroffMachineNetconfPoweroffMachinePost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PoweroffMachineNetconfPoweroffMachinePostMutationResult = NonNullable<Awaited<ReturnType<typeof poweroffMachineNetconfPoweroffMachinePost>>>

    export type PoweroffMachineNetconfPoweroffMachinePostMutationError = unknown

    /**
 * @summary Poweroff Machine
 */
export const usePoweroffMachineNetconfPoweroffMachinePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof poweroffMachineNetconfPoweroffMachinePost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof poweroffMachineNetconfPoweroffMachinePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPoweroffMachineNetconfPoweroffMachinePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Reboot Machine
 */
export type rebootMachineNetconfRebootMachinePostResponse200 = {
  data: unknown
  status: 200
}

export type rebootMachineNetconfRebootMachinePostResponseSuccess = (rebootMachineNetconfRebootMachinePostResponse200) & {
  headers: Headers;
};
;

export type rebootMachineNetconfRebootMachinePostResponse = (rebootMachineNetconfRebootMachinePostResponseSuccess)

export const getRebootMachineNetconfRebootMachinePostUrl = () => {




  return `/netconf/reboot-machine`
}

export const rebootMachineNetconfRebootMachinePost = async ( options?: RequestInit): Promise<rebootMachineNetconfRebootMachinePostResponse> => {

  const res = await fetch(getRebootMachineNetconfRebootMachinePostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rebootMachineNetconfRebootMachinePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rebootMachineNetconfRebootMachinePostResponse
}




export const getRebootMachineNetconfRebootMachinePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rebootMachineNetconfRebootMachinePost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof rebootMachineNetconfRebootMachinePost>>, TError,void, TContext> => {

const mutationKey = ['rebootMachineNetconfRebootMachinePost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rebootMachineNetconfRebootMachinePost>>, void> = () => {


          return  rebootMachineNetconfRebootMachinePost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RebootMachineNetconfRebootMachinePostMutationResult = NonNullable<Awaited<ReturnType<typeof rebootMachineNetconfRebootMachinePost>>>

    export type RebootMachineNetconfRebootMachinePostMutationError = unknown

    /**
 * @summary Reboot Machine
 */
export const useRebootMachineNetconfRebootMachinePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rebootMachineNetconfRebootMachinePost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rebootMachineNetconfRebootMachinePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRebootMachineNetconfRebootMachinePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Rpc
 */
export type rpcNetconfRpcPostResponse200 = {
  data: unknown
  status: 200
}

export type rpcNetconfRpcPostResponseSuccess = (rpcNetconfRpcPostResponse200) & {
  headers: Headers;
};
;

export type rpcNetconfRpcPostResponse = (rpcNetconfRpcPostResponseSuccess)

export const getRpcNetconfRpcPostUrl = () => {




  return `/netconf/rpc`
}

export const rpcNetconfRpcPost = async ( options?: RequestInit): Promise<rpcNetconfRpcPostResponse> => {

  const res = await fetch(getRpcNetconfRpcPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rpcNetconfRpcPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rpcNetconfRpcPostResponse
}




export const getRpcNetconfRpcPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rpcNetconfRpcPost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof rpcNetconfRpcPost>>, TError,void, TContext> => {

const mutationKey = ['rpcNetconfRpcPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rpcNetconfRpcPost>>, void> = () => {


          return  rpcNetconfRpcPost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RpcNetconfRpcPostMutationResult = NonNullable<Awaited<ReturnType<typeof rpcNetconfRpcPost>>>

    export type RpcNetconfRpcPostMutationError = unknown

    /**
 * @summary Rpc
 */
export const useRpcNetconfRpcPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rpcNetconfRpcPost>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rpcNetconfRpcPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRpcNetconfRpcPostMutationOptions(options), queryClient);
    }
