/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Connection,
  HTTPValidationError
} from '../model';





/**
 * @summary Connect
 */
export type connectResponse200 = {
  data: unknown
  status: 200
}

export type connectResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type connectResponseSuccess = (connectResponse200) & {
  headers: Headers;
};
export type connectResponseError = (connectResponse422) & {
  headers: Headers;
};

export type connectResponse = (connectResponseSuccess | connectResponseError)

export const getConnectUrl = () => {




  return `/connect`
}

export const connect = async (connection: Connection, options?: RequestInit): Promise<connectResponse> => {

  const res = await fetch(getConnectUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      connection,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: connectResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as connectResponse
}




export const getConnectMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connect>>, TError,{data: Connection}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof connect>>, TError,{data: Connection}, TContext> => {

const mutationKey = ['connect'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connect>>, {data: Connection}> = (props) => {
          const {data} = props ?? {};

          return  connect(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectMutationResult = NonNullable<Awaited<ReturnType<typeof connect>>>
    export type ConnectMutationBody = Connection
    export type ConnectMutationError = HTTPValidationError

    /**
 * @summary Connect
 */
export const useConnect = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connect>>, TError,{data: Connection}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connect>>,
        TError,
        {data: Connection},
        TContext
      > => {
      return useMutation(getConnectMutationOptions(options), queryClient);
    }
    /**
 * @summary Disconnect Route
 */
export type disconnectResponse200 = {
  data: string[]
  status: 200
}

export type disconnectResponseSuccess = (disconnectResponse200) & {
  headers: Headers;
};
;

export type disconnectResponse = (disconnectResponseSuccess)

export const getDisconnectUrl = () => {




  return `/connect`
}

export const disconnect = async ( options?: RequestInit): Promise<disconnectResponse> => {

  const res = await fetch(getDisconnectUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: disconnectResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as disconnectResponse
}




export const getDisconnectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnect>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof disconnect>>, TError,void, TContext> => {

const mutationKey = ['disconnect'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disconnect>>, void> = () => {


          return  disconnect(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DisconnectMutationResult = NonNullable<Awaited<ReturnType<typeof disconnect>>>

    export type DisconnectMutationError = unknown

    /**
 * @summary Disconnect Route
 */
export const useDisconnect = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnect>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disconnect>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDisconnectMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Available Modules
 */
export type getAvailableModulesResponse200 = {
  data: string[]
  status: 200
}

export type getAvailableModulesResponseSuccess = (getAvailableModulesResponse200) & {
  headers: Headers;
};
;

export type getAvailableModulesResponse = (getAvailableModulesResponseSuccess)

export const getGetAvailableModulesUrl = () => {




  return `/modules/available`
}

export const getAvailableModules = async ( options?: RequestInit): Promise<getAvailableModulesResponse> => {

  const res = await fetch(getGetAvailableModulesUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAvailableModulesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAvailableModulesResponse
}





export const getGetAvailableModulesQueryKey = () => {
    return [
    `/modules/available`
    ] as const;
    }


export const getGetAvailableModulesQueryOptions = <TData = Awaited<ReturnType<typeof getAvailableModules>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableModules>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAvailableModulesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailableModules>>> = ({ signal }) => getAvailableModules({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAvailableModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvailableModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailableModules>>>
export type GetAvailableModulesQueryError = unknown


export function useGetAvailableModules<TData = Awaited<ReturnType<typeof getAvailableModules>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailableModules>>,
          TError,
          Awaited<ReturnType<typeof getAvailableModules>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailableModules<TData = Awaited<ReturnType<typeof getAvailableModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailableModules>>,
          TError,
          Awaited<ReturnType<typeof getAvailableModules>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailableModules<TData = Awaited<ReturnType<typeof getAvailableModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableModules>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Available Modules
 */

export function useGetAvailableModules<TData = Awaited<ReturnType<typeof getAvailableModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableModules>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAvailableModulesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Modules
 */
export type getModulesResponse200 = {
  data: string[]
  status: 200
}

export type getModulesResponseSuccess = (getModulesResponse200) & {
  headers: Headers;
};
;

export type getModulesResponse = (getModulesResponseSuccess)

export const getGetModulesUrl = () => {




  return `/modules/`
}

export const getModules = async ( options?: RequestInit): Promise<getModulesResponse> => {

  const res = await fetch(getGetModulesUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getModulesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getModulesResponse
}





export const getGetModulesQueryKey = () => {
    return [
    `/modules/`
    ] as const;
    }


export const getGetModulesQueryOptions = <TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModulesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModules>>> = ({ signal }) => getModules({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getModules>>>
export type GetModulesQueryError = unknown


export function useGetModules<TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModules>>,
          TError,
          Awaited<ReturnType<typeof getModules>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModules<TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModules>>,
          TError,
          Awaited<ReturnType<typeof getModules>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModules<TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Modules
 */

export function useGetModules<TData = Awaited<ReturnType<typeof getModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModules>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModulesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Download Module
 */
export type downloadModuleResponse200 = {
  data: unknown
  status: 200
}

export type downloadModuleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type downloadModuleResponseSuccess = (downloadModuleResponse200) & {
  headers: Headers;
};
export type downloadModuleResponseError = (downloadModuleResponse422) & {
  headers: Headers;
};

export type downloadModuleResponse = (downloadModuleResponseSuccess | downloadModuleResponseError)

export const getDownloadModuleUrl = (moduleName: string,) => {




  return `/modules/${moduleName}/download`
}

export const downloadModule = async (moduleName: string, options?: RequestInit): Promise<downloadModuleResponse> => {

  const res = await fetch(getDownloadModuleUrl(moduleName),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: downloadModuleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as downloadModuleResponse
}




export const getDownloadModuleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof downloadModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof downloadModule>>, TError,{moduleName: string}, TContext> => {

const mutationKey = ['downloadModule'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof downloadModule>>, {moduleName: string}> = (props) => {
          const {moduleName} = props ?? {};

          return  downloadModule(moduleName,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DownloadModuleMutationResult = NonNullable<Awaited<ReturnType<typeof downloadModule>>>

    export type DownloadModuleMutationError = HTTPValidationError

    /**
 * @summary Download Module
 */
export const useDownloadModule = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof downloadModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof downloadModule>>,
        TError,
        {moduleName: string},
        TContext
      > => {
      return useMutation(getDownloadModuleMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Module
 */
export type deleteModuleResponse200 = {
  data: unknown
  status: 200
}

export type deleteModuleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteModuleResponseSuccess = (deleteModuleResponse200) & {
  headers: Headers;
};
export type deleteModuleResponseError = (deleteModuleResponse422) & {
  headers: Headers;
};

export type deleteModuleResponse = (deleteModuleResponseSuccess | deleteModuleResponseError)

export const getDeleteModuleUrl = (moduleName: string,) => {




  return `/modules/${moduleName}`
}

export const deleteModule = async (moduleName: string, options?: RequestInit): Promise<deleteModuleResponse> => {

  const res = await fetch(getDeleteModuleUrl(moduleName),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteModuleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteModuleResponse
}




export const getDeleteModuleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,{moduleName: string}, TContext> => {

const mutationKey = ['deleteModule'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteModule>>, {moduleName: string}> = (props) => {
          const {moduleName} = props ?? {};

          return  deleteModule(moduleName,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteModuleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteModule>>>

    export type DeleteModuleMutationError = HTTPValidationError

    /**
 * @summary Delete Module
 */
export const useDeleteModule = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,{moduleName: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteModule>>,
        TError,
        {moduleName: string},
        TContext
      > => {
      return useMutation(getDeleteModuleMutationOptions(options), queryClient);
    }
