name: Frontend tests

on:
  push:
    branches: [main]
    paths:
      - "manager-frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "manager-frontend/**"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: manager-frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: manager-frontend/package-lock.json
      - run: npm ci
      - run: npx @biomejs/biome ci .
